### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by xudafeng** [macacajs/XCTestWD#10]
- [x] 真机描述
- [x] 命令行启动描述，端口占用说明
- [x] ElementType 映射说明，贴文档链接

**Comment by SamuelZhaoY** [comment]
完成 以上三点任务， 待验收

**Comment by SamuelZhaoY** [comment]
<img width="843" alt="2017-12-14 10 55 14" src="https://user-images.githubusercontent.com/8198256/33973561-912c0dde-e0be-11e7-824c-bfa5df42e889.png">
<img width="267" alt="2017-12-14 10 56 33" src="https://user-images.githubusercontent.com/8198256/33973562-9153137a-e0be-11e7-9ef0-b2d06bbd32c8.png">

**Comment by adudurant** [comment]
Excellent！
