### ISSUE TITLE
XCODE 9.1 编译报错

### ISSUE THREAD

**Issue by WilliamStark** [macacajs/XCTestWD#103]
如图：

![image](https://user-images.githubusercontent.com/6532570/32309307-bb6f18e8-bf58-11e7-9339-50a135989269.png)

**Comment by xudafeng** [comment]
升级新版

**Comment by WilliamStark** [comment]
已更新至1.3.3版本 还是编译不过
/usr/local/lib/node_modules/macaca-ios/node_modules/.1.3.3@xctestwd/XCTestWD/XCTestWDUITests/Server/Controllers/XCTestWDStatusController.swift:10:8: Module compiled with Swift 4.0 cannot be imported in Swift 3.2.2: /usr/local/lib/node_modules/macaca-ios/node_modules/.1.3.3@xctestwd/XCTestWD/../Carthage/Build/iOS/Swifter.framework/Modules/Swifter.swiftmodule/arm64.swiftmodule
