### ISSUE TITLE
xcode9 iOS11套餐疑问

### ISSUE THREAD

**Issue by huanglik** [macacajs/XCTestWD#107]
XCode version 9.0 and above.
iOS version 11.0 and above. （there is significant change on XCUITest interfaces and system private headers, hence we decide to support newest OS version only）

想问下，如果使用了xcode9， 是不是只能在ios11及以上的手机系统才能正常运行？

发现使用xcode9后，无法运行ios11以下的手机了，这是做了什么改变么，具体XCUITest接口是什么改变，能不能说一下？

**Comment by adudurant** [comment]
ios11需要xcode9来调试，同时xcode的升级会有一些私有库的改变，一些接口的变动，具体可以去看代码
