### ISSUE TITLE
Code=14 "Test operation was canceled

### ISSUE THREAD

**Issue by yc247796047** [macacajs/XCTestWD#108]
help~!!!!
10:10:31.372 xcodebuild[84926:6907410] Beginning test session XCTestWDUITests-9BE04E75-733E-41D7-92FB-4759C89B7AAA at 2017-11-24 10:10:31.370 with Xcode 9A235 on target <DVTiPhoneSimulator: 0x7f9224fb4da0> {
		SimDevice: iPhone 6s (4593171D-F6F3-437A-A8C1-C9F5781811ED, iOS 11.0, Booted)
} (11.0 (15A372))
10:10:31.372 xcodebuild[84926:6907410] 	/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
test
-project
/usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
-scheme
XCTestWD
-destination
id=4593171D-F6F3-437A-A8C1-C9F5781811ED
XCTESTWD_PORT=8001
10:10:31.372 xcodebuild[84926:6907410] Launching with Xcode.IDEFoundation.Launcher.PosixSpawn
10:10:31.375 xcodebuild[84926:6907410] Test standard output and standard error is at /var/folders/2p/970k23wj3p3dzf5049crvrkm0000gn/T/com.apple.dt.XCTest/IDETestRunSession-433BA4F7-797B-41F4-9307-A119055C538B/XCTestWDUITests-4BB13A85-6EEB-4739-B80F-BC101A4E3EB0/StandardOutputAndStandardError.txt
10:10:32.288 xcodebuild[84926:6907410] Test operation failure: Test operation was canceled.
10:10:32.289 xcodebuild[84926:6907410] _finishWithError:Error Domain=IDETestOperationsObserverErrorDomain Code=14 "Test operation was canceled." UserInfo={NSLocalizedDescription=Test operation was canceled.}

**Comment by adudurant** [comment]
Pls offer more information

**Comment by yc247796047** [comment]
macaca-doctor version: 2.0.4


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.1.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 9.0
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.26.2

  Android checklist:

  JAVA version is `1.8.0_45`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/yangchun/Documents/macbook/yangchun/software/adt-bundle-mac-x86_64-20140702/sdk`
  Platforms is set to `/Users/yangchun/Documents/macbook/yangchun/software/adt-bundle-mac-x86_64-20140702/sdk/platforms/android-26`
  ADB tool is set to `/Users/yangchun/Documents/macbook/yangchun/software/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb`
  gradle is installed, version: 4.3

  Installed driver list:

  android: 2.0.40
  chrome: 1.0.6 [out-of-date]
  electron: 1.1.11 [out-of-date]
  ios: 2.0.29


i use macaca and run :macaca run --reporter mochawesome -d ./macaca-test/mobile-app-sample.test.js

get /Users/yangchun/.macaca-temp/ios-app-bootstrap.zip from cache
sha:d2e65bba467659ef610b369f2ee599c1
CFBundleIdentifier is xudafeng.ios-app-bootstrap
Get bundleId xudafeng.ios-app-bootstrap from plist /var/folders/2p/970k23wj3p3dzf5049crvrkm0000gn/T/ios-app-bootstrap.app/Info.plist
XCTestWD version: 1.3.9
Read simulator log at: /var/folders/2p/970k23wj3p3dzf5049crvrkm0000gn/T/com.apple.dt.XCTest/IDETestRunSession-49F4E3C7-22A7-46B4-9BF3-6541255B2213/XCTestWDUITests-9C887AD3-4A99-406A-B2F6-6E6B0D6E714C/StandardOutputAndStandardError.txt
Read simulator log at: /var/folders/2p/970k23wj3p3dzf5049crvrkm0000gn/T/com.apple.dt.XCTest/IDETestRunSession-49F4E3C7-22A7-46B4-9BF3-6541255B2213/XCTestWDUITests-9C887AD3-4A99-406A-B2F6-6E6B0D6E714C/StandardOutputAndStandardError.txt
Read simulator log at: /var/folders/2p/970k23wj3p3dzf5049crvrkm0000gn/T/com.apple.dt.XCTest/IDETestRunSession-49F4E3C7-22A7-46B4-9BF3-6541255B2213/XCTestWDUITests-9C887AD3-4A99-406A-B2F6-6E6B0D6E714C/StandardOutputAndStandardError.txt
get /Users/yangchun/.macaca-temp/ios-app-bootstrap.zip from cache
sha:d2e65bba467659ef610b369f2ee599c1
CFBundleIdentifier is xudafeng.ios-app-bootstrap
Get bundleId xudafeng.ios-app-bootstrap from plist /var/folders/2p/970k23wj3p3dzf5049crvrkm0000gn/T/ios-app-bootstrap.app/Info.plist
XCTestWD version: 1.3.9
Read simulator log at: /var/folders/2p/970k23wj3p3dzf5049crvrkm0000gn/T/com.apple.dt.XCTest/IDETestRunSession-FD3ABDC4-248C-47D1-86DF-CAB8A6713571/XCTestWDUITests-73E3393A-BD7E-49FF-B768-16CDE0C025B1/StandardOutputAndStandardError.txt
Read simulator log at: /var/folders/2p/970k23wj3p3dzf5049crvrkm0000gn/T/com.apple.dt.XCTest/IDETestRunSession-FD3ABDC4-248C-47D1-86DF-CAB8A6713571/XCTestWDUITests-73E3393A-BD7E-49FF-B768-16CDE0C025B1/StandardOutputAndStandardError.txt
Read simulator log at: /var/folders/2p/970k23wj3p3dzf5049crvrkm0000gn/T/com.apple.dt.XCTest/IDETestRunSession-FD3ABDC4-248C-47D1-86DF-CAB8A6713571/XCTestWDUITests-73E3393A-BD7E-49FF-B768-16CDE0C025B1/StandardOutputAndStandardError.txt

**Comment by xudafeng** [comment]
due to `xcodebuild version: 9.0`

@Chan-Chun
