### ISSUE TITLE
xcode 9 ios 10、11 wd/hub/source 特别慢

### ISSUE THREAD

**Issue by pluie-cloud** [macacajs/XCTestWD#110]
xcode 9 ios 10、11 wd/hub/source 特别慢 基本上都是15s 建议大家不要升级xcode 我要哭了

**Comment by adudurant** [comment]
有些app 确实比较慢，持续优化中。但是，可以根据自己app做些定制化修改，能达到提速目的。

**Comment by pluie-cloud** [comment]
@adudurant 大神 我看了下 代码一抹一样  但是就是xcode 9 比xcode 8 慢十倍

**Comment by SamuelZhaoY** [comment]
@pluie-cloud 这句话是以真机为前提的模拟器并无此问题，现在其他测试工具都存在此问题.  受到相同接口的制约

**Comment by pluie-cloud** [comment]
@SamuelZhaoY  好的 主要是现在都是用得真机 啥时候真机不慢了 我再切换到xcode 9好了
谢谢

**Comment by SamuelZhaoY** [comment]
真机的问题 受制于系统库， 后续会采用Predicate 方法进行优化， 减少对source 的依赖
