### ISSUE TITLE
xctest-client中moment问题

### ISSUE THREAD

**Issue by butterflyingdog** [macacajs/XCTestWD#112]
xctest-client.js 脚本，startDeviceLog()中，通过devicelog获取了设备的当前操作时间，并与mac电脑当前时间进行了比较，代码如下，但如果手机时间比mac电脑时间慢的情况下，程序就不会往下执行了。为什么会有这样一个设计呢？

```
if (lasthit > this.moment) {
              this.configUrl(url);
              resolve();
            }
```

**Comment by xudafeng** [comment]
@butterflyingdog 很抱歉，这是错误的实现，会在最近修复。

**Comment by xudafeng** [comment]
https://github.com/macacajs/XCTestWD/commit/21e0f0748b7541ab3dc9ce0575c6072482049618
