### ISSUE TITLE
错误码完善

### ISSUE THREAD

**Issue by xudafeng** [macacajs/XCTestWD#113]
- socket hang up 问题导致的原因较多，需要暴露出来给进一步的用户指引

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/763

**Comment by SamuelZhaoY** [comment]
https://stackoverflow.com/questions/6411549/where-is-logfile-stored-using-cocoalumberjack  引入日志生成器， 用户可在模拟器， 或者设备中通过以上方法捞取日志文件.

**Comment by SamuelZhaoY** [comment]
见问题： https://github.com/macacajs/XCTestWD/issues/66
