### ISSUE TITLE
build后挂掉了，请求帮助～

### ISSUE THREAD

**Issue by GeorgeZh** [macacajs/XCTestWD#117]
dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /Users/george/Library/Developer/CoreSimulator/Devices/CCEC27BA-600F-4F90-8032-4595E75A7892/data/Containers/Bundle/Application/20BB16A4-A6F8-4755-9B5C-203147C224C9/XCTestWDDemo.app/Frameworks/libswiftXCTest.dylib
  Reason: image not found

Use of undeclared type 'XCTestWDServer'

已使用carthage update

**Comment by adudurant** [comment]
There is something wrong with your environment.Please try again according to the instructions in the front page.

**Comment by SamuelZhaoY** [comment]
Please update to current version .18 which solves the compilation issue . We have built the XCTestWD into a standard swift module which can be integrated into your own UI Test Project. Hence the recent refactoring might cause some compilation issue in early versions.

**Comment by GeorgeZh** [comment]
问题已解决，感谢
