### ISSUE TITLE
 使用xcode9.1编译XCTestWD出错

### ISSUE THREAD

**Issue by 789dry** [macacajs/XCTestWD#118]
使用xcode9.1编译XCTestWD出错，错误信息如下：
Type 'XCUIElement' has no member 'ElementType'

**Comment by jack-github** [comment]
XCTestWD降一个版本就正常了。。。。

**Comment by 789dry** [comment]
这个有啥方法将macaca的ios驱动替换为webdriveragent吗？感觉整套的坑较多，还是留一手比较好，哈哈

**Comment by adudurant** [comment]
底层一样的都是苹果的私有api

**Comment by SamuelZhaoY** [comment]
@789dry  @jack-github 这个是本身swift 版本的问题， 跟Xcode 无关.  目前使用的是Swift4 语法.  以正视听 :)

**Comment by jack-github** [comment]
@SamuelZhaoY 为什么iOS，在录制的时候一些控件会无法识别？

**Comment by SamuelZhaoY** [comment]
与当前组建visibility， hidden 属性有关， iOS 应用中的所有默认组建是可以识别的，请参考app-inspector 在 iOS springboard 的使用

**Comment by liweiting** [comment]
@jack-github XCTestWD这个是和macaca-ios一起装上的，是降macaca-ios的版本还是单独下一个XCTestWD替换了
