### ISSUE TITLE
build fails with xcode 9.3

### ISSUE THREAD

**Issue by xudafeng** [macacajs/XCTestWD#122]
https://github.com/macacajs/xctestwd-frameworks-9.3

**Comment by xudafeng** [comment]
due to https://github.com/cezheng/Fuzi/issues/77

**Comment by lovexiaov** [comment]
我自己 fork 了一份 Fuzi 的仓库，删除了 modulemap 文件，增加了 `-lxml2` linker flags. 把 xctestwd 目录下的 Cartfile 文件中对应的行修改为 `github "lovexiaov/Fuzi"`后，可以正常编译了~

**Comment by SamuelZhaoY** [comment]
@lovexiaov 谢谢反馈， 目前也进行了修复.  已支持xcode 9.3
