### ISSUE TITLE
编译，安装后 测试失败  大神们，求解啊

### ISSUE THREAD

**Issue by xiaomingstudy** [macacajs/XCTestWD#123]
dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /var/containers/Bundle/Application/FAFD159A-93CE-4595-9D8F-4785C6A131F9/XCTestWDUITests-Runner.app/XCTestWDUITests-Runner
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/FAFD159A-93CE-4595-9D8F-4785C6A131F9/XCTestWDUITests-Runner.app/Frameworks/XCTest.framework/XCTest: code signing blocked mmap() of '/private/var/containers/Bundle/Application/FAFD159A-93CE-4595-9D8F-4785C6A131F9/XCTestWDUITests-Runner.app/Frameworks/XCTest.framework/XCTest'
	/private/var/containers/Bundle/Application/FAFD159A-93CE-4595-9D8F-4785C6A131F9/XCTestWDUITests-Runner.app/Frameworks/XCTest.framework/XCTest: code signing blocked mmap() of '/private/var/containers/Bundle/Application/FAFD159A-93CE-4595-9D8F-4785C6A131F9/XCTestWDUITests-Runner.app/Frameworks/XCTest.framework/XCTest'
Message from debugger: Terminated due to signal 6

已使用carthage update 
Xcode 9.3

**Comment by SamuelZhaoY** [comment]
请注意在真机测试前，为XCTestWDUITest 增加profile 授权.  ‘code signing blocked’
