### ISSUE TITLE
please refer issue #184 raised under app-inspector

### ISSUE THREAD

**Issue by rdhandapani88** [macacajs/XCTestWD#124]
Issue raised for Error while running XCTestWD - Use of undeclared type 'XCTestWDServer' , because of that app-inspector is not working #184
![screen shot 2018-04-05 at 1 26 21 pm](https://user-images.githubusercontent.com/32144304/38381854-17126dfc-38d6-11e8-85af-267214952e29.png)

**Comment by SamuelZhaoY** [comment]
Seems you are running for real device, in that case, please build the target 'XCTestWD' first and then run XCTestWDUITest, ensure you have provide the suitable provision profile for device
