### ISSUE TITLE
Build failed in Mac OS version 10.13 and Xcode version 9.3

### ISSUE THREAD

**Issue by tlllly** [macacajs/XCTestWD#125]
Mac OS: 10.13.4  Xcode version： 9.3(9E145)
1、cd /XCTestWd directory/
2、Execute command： carthage update

I got below error message, please help to solve this issue, thanks!
Building scheme "Fuzi" in Fuzi.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/autotest/git/XCTestWD/Carthage/Checkouts/Fuzi/Fuzi.xcworkspace -scheme Fuzi -configuration Release -derivedDataPath /Users/autotest/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/Fuzi/1.0.1 -sdk watchos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/5h/fq87rwbs4vx21fv0138b50n40000gp/T/Fuzi SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/autotest/git/XCTestWD/Carthage/Checkouts/Fuzi)

...

/Users/autotest/git/XCTestWD/Carthage/Checkouts/Fuzi/Sources/Fuzi.h:22:9: error: could not build module 'Foundation'
#import <Foundation/Foundation.h>
        ^
<unknown>:0: error: could not build Objective-C module 'Fuzi'

** ARCHIVE FAILED **

The following build commands failed:
	CompileSwift normal armv7k
	CompileSwiftSources normal armv7k com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by SamuelZhaoY** [comment]
refer to this https://github.com/macacajs/XCTestWD/issues/122
