### ISSUE TITLE
XCTestWD编译报错Missing required module 'libxmlLiKui'

### ISSUE THREAD

**Issue by Fengyongming0311** [macacajs/XCTestWD#127]
环境：macOS 10.13.4
XCode：9.4
XCTestWD  Version 1.3.30
按照官网教程安装app-inspector
DEVELOPMENT_TEAM_ID=X3G9DD3JFY npm i app-inspector -g
安装完之后 终端运行命令
app-inspector -u 662ec68d7cb948a8c15de13db97f432d30b467b5 –verbose
报错：

xctest client exit with code: 65,signal:null
devicelog exit with code: null, signal: SIGKILL
undefined
>> iOS device started: 662ec68d7cb948a8c15de13db97f432d30b467b5
>> inspector start at: http://192.168.205.132:5678
  <-- GET /

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)

![undefind00](https://user-images.githubusercontent.com/33747372/40776175-8ffdb008-64fc-11e8-9b5a-d813fd4f6cfa.png)
![undefind](https://user-images.githubusercontent.com/33747372/40776178-9377a036-64fc-11e8-9e9f-b20fdb21b061.png)

TestHome帖子里说进入XCTestWD里配置好信息后编译报错
Missing required module 'libxmlLiKui'

![bug](https://user-images.githubusercontent.com/33747372/40775713-505cccbe-64fb-11e8-82d5-cacb06e945a3.png)

已经尝试手动装过libxml2 还是报错，请开发者们帮忙看一下问题，谢谢

**Comment by xudafeng** [comment]
https://github.com/macacajs/XCTestWD/commit/21352e36481d107009692f6900ca7f473a246051
