### ISSUE TITLE
monkey 自身挂掉了

### ISSUE THREAD

**Issue by gaoyucao** [macacajs/XCTestWD#128]
![image](https://user-images.githubusercontent.com/25318411/41694810-b6c0703e-753e-11e8-9aa5-82fab794755d.png)
[Session-XCTestWDUITests-2018-06-21_003334-qFSvJu.log](https://github.com/macacajs/XCTestWD/files/2121835/Session-XCTestWDUITests-2018-06-21_003334-qFSvJu.log)

**Comment by adudurant** [comment]
Offer more information.

**Comment by SamuelZhaoY** [comment]
请根据 https://github.com/macacajs/XCTestWD 上的debug 提示查看问题原因
