### ISSUE TITLE
多机(真机)并行,执行xcodebuild命令时，上一个安装完成且正在运行的手机会卸载重新安装xctestwd。

### ISSUE THREAD

**Issue by xiaomingstudy** [macacajs/XCTestWD#131]
>> helper.js:32:24 [worker:1] pid:59578 xctest client proxy error with: Error: socket hang up
>> xctest-client.js:44:14 [worker:1] pid:59578 Uncaught Exception: Error: >> helper.js:32:24 [worker:1] pid:59578 xctest client proxy error with: Error: socket hang up
    at Logger.error (/Users/ceshizhongxinmacbook/macaca/reliable-macaca-slave/node_modules/xlogger/lib/xlogger.js:169:9)
    at Request.request [as _callback] (/Users/ceshizhongxinmacbook/macaca/reliable-macaca-slave/common/helper.js:32:24)
    at self.callback (/Users/ceshizhongxinmacbook/macaca/reliable-macaca-slave/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/Users/ceshizhongxinmacbook/macaca/reliable-macaca-slave/node_modules/request/request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketOnEnd (_http_client.js:423:9)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
/Users/ceshizhongxinmacbook/macaca/reliable-macaca-slave/node_modules/xlogger/lib/xlogger.js:169
  throw new Error(res);
  ^

Error: >> xctest-client.js:44:14 [worker:1] pid:59578 Uncaught Exception: Error: >> helper.js:32:24 [worker:1] pid:59578 xctest client proxy error with: Error: socket hang up
    at Logger.error (/Users/ceshizhongxinmacbook/macaca/reliable-macaca-slave/node_modules/xlogger/lib/xlogger.js:169:9)
    at Request.request [as _callback] (/Users/ceshizhongxinmacbook/macaca/reliable-macaca-slave/common/helper.js:32:24)
    at self.callback (/Users/ceshizhongxinmacbook/macaca/reliable-macaca-slave/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/Users/ceshizhongxinmacbook/macaca/reliable-macaca-slave/node_modules/request/request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketOnEnd (_http_client.js:423:9)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Logger.error (/Users/ceshizhongxinmacbook/macaca/reliable-macaca-slave/node_modules/xlogger/lib/xlogger.js:169:9)
    at process.on (/Users/ceshizhongxinmacbook/macaca/reliable-macaca-slave/node_modules/xctestwd/lib/xctest-client.js:44:14)
    at emitOne (events.js:121:20)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:378:26)

**Comment by adudurant** [comment]
端口串了  指定端口

**Comment by xiaomingstudy** [comment]
xcodebuild -project XCTestWD.xcodeproj \
                        -scheme XCTestWDUITests \
                        -destination 'platform=iOS','id=xxxxxxxx8322' \
                        XCTESTWD_PORT=8001 \
                        clean test
xcodebuild -project XCTestWD.xcodeproj \
                     -scheme XCTestWDUITests \
                     -destination 'platform=iOS,id=xxxxxxxxxxxxx91ff9' \
                     XCTESTWD_PORT=8005 \
                     clean test

我在命令行执行这两条命令，第二条会把第一条所指向手机的XCTestWDUITests 卸载安装。而且两条命令都会报错。
日志如下：
        
      8322：Restarting after unexpected exit or crash in XCTextWDRunner/testRunner(); summary will include totals from previous launches.

Test Suite 'Selected tests' started at 2018-08-01 09:04:45.115
Test Suite 'XCTestWDUITests.xctest' started at 2018-08-01 09:04:45.117
Test Suite 'XCTestWDUITests.xctest' failed at 2018-08-01 09:04:45.117.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.001) seconds
Test Suite 'Selected tests' failed at 2018-08-01 09:04:45.119.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.003) seconds
** TEST FAILED **

91ff9：iPhoneConnect: installApplicationBundleAtPath:withOptions:andError:withCallback: failed with {
    NSLocalizedDescription = "App installation failed";
    NSLocalizedFailureReason = "This application\U2019s application-identifier entitlement does not match that of the installed application. These values must match for an upgrade to be allowed.";
    NSLocalizedRecoverySuggestion = "This application\U2019s application-identifier entitlement does not match that of the installed application. These values must match for an upgrade to be allowed.";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x0000000115c6df4f DTDKCreateNSError + 113
	1   DTDeviceKitBase                     0x0000000115c6e793 DTDK_AMDErrorToNSError + 1135
	2   DTDeviceKitBase                     0x0000000115caf4f1 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 158
	3   DVTFoundation                       0x000000010c182be2 DVTInvokeWithStrongOwnership + 73
	4   DTDeviceKitBase                     0x0000000115caf1af -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1301
	5   IDEiOSSupportCore                   0x0000000115ba50ff __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.340 + 4009
	6   DVTFoundation                       0x000000010c2a5a91 __DVTDispatchAsync_block_invoke + 806
	7   libdispatch.dylib                   0x00007fff7a38d5fa _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff7a385db8 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff7a39a217 _dispatch_queue_serial_drain + 635
	10  libdispatch.dylib                   0x00007fff7a38d166 _dispatch_queue_invoke + 373
	11  libdispatch.dylib                   0x00007fff7a39af0d _dispatch_root_queue_drain_deferred_wlh + 332
	12  libdispatch.dylib                   0x00007fff7a39ed21 _dispatch_workloop_worker_thread + 880
	13  libsystem_pthread.dylib             0x00007fff7a6d6fd2 _pthread_wqthread + 980
	14  libsystem_pthread.dylib             0x00007fff7a6d6be9 start_wqthread + 13
);
}
2018-08-01 09:04:35.220 xcodebuild[60426:547634]  iPhoneConnect: Failed to install /Users/ceshizhongxinmacbook/Library/Developer/Xcode/DerivedData/XCTestWD-fqqzmekkadflgceviwqbjjtczdhj/Build/Products/Debug-iphoneos/XCTestWDUITests-Runner.app - error Error Domain=com.apple.dtdevicekit Code=-402652994 "App installation failed" UserInfo={NSLocalizedDescription=App installation failed, com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x0000000115c6df4f DTDKCreateNSError + 113
	1   DTDeviceKitBase                     0x0000000115c6e793 DTDK_AMDErrorToNSError + 1135
	2   DTDeviceKitBase                     0x0000000115caf4f1 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 158
	3   DVTFoundation                       0x000000010c182be2 DVTInvokeWithStrongOwnership + 73
	4   DTDeviceKitBase                     0x0000000115caf1af -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1301
	5   IDEiOSSupportCore                   0x0000000115ba50ff __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.340 + 4009
	6   DVTFoundation                       0x000000010c2a5a91 __DVTDispatchAsync_block_invoke + 806
	7   libdispatch.dylib                   0x00007fff7a38d5fa _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff7a385db8 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff7a39a217 _dispatch_queue_serial_drain + 635
	10  libdispatch.dylib                   0x00007fff7a38d166 _dispatch_queue_invoke + 373
	11  libdispatch.dylib                   0x00007fff7a39af0d _dispatch_root_queue_drain_deferred_wlh + 332
	12  libdispatch.dylib                   0x00007fff7a39ed21 _dispatch_workloop_worker_thread + 880
	13  libsystem_pthread.dylib             0x00007fff7a6d6fd2 _pthread_wqthread + 980
	14  libsystem_pthread.dylib             0x00007fff7a6d6be9 start_wqthread + 13
), NSLocalizedRecoverySuggestion=This application’s application-identifier entitlement does not match that of the installed application. These values must match for an upgrade to be allowed., NSLocalizedFailureReason=This application’s application-identifier entitlement does not match that of the installed application. These values must match for an upgrade to be allowed.}
2018-08-01 09:04:35.227 xcodebuild[60426:547243] Error Domain=com.apple.dtdevicekit Code=-402652994 "App installation failed" UserInfo={NSLocalizedDescription=App installation failed, com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x0000000115c6df4f DTDKCreateNSError + 113
	1   DTDeviceKitBase                     0x0000000115c6e793 DTDK_AMDErrorToNSError + 1135
	2   DTDeviceKitBase                     0x0000000115caf4f1 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 158
	3   DVTFoundation                       0x000000010c182be2 DVTInvokeWithStrongOwnership + 73
	4   DTDeviceKitBase                     0x0000000115caf1af -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1301
	5   IDEiOSSupportCore                   0x0000000115ba50ff __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.340 + 4009
	6   DVTFoundation                       0x000000010c2a5a91 __DVTDispatchAsync_block_invoke + 806
	7   libdispatch.dylib                   0x00007fff7a38d5fa _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff7a385db8 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff7a39a217 _dispatch_queue_serial_drain + 635
	10  libdispatch.dylib                   0x00007fff7a38d166 _dispatch_queue_invoke + 373
	11  libdispatch.dylib                   0x00007fff7a39af0d _dispatch_root_queue_drain_deferred_wlh + 332
	12  libdispatch.dylib                   0x00007fff7a39ed21 _dispatch_workloop_worker_thread + 880
	13  libsystem_pthread.dylib             0x00007fff7a6d6fd2 _pthread_wqthread + 980
	14  libsystem_pthread.dylib             0x00007fff7a6d6be9 start_wqthread + 13
), NSLocalizedRecoverySuggestion=This application’s application-identifier entitlement does not match that of the installed application. These values must match for an upgrade to be allowed., NSLocalizedFailureReason=This application’s application-identifier entitlement does not match that of the installed application. These values must match for an upgrade to be allowed.}
2018-08-01 09:04:35.227 xcodebuild[60426:547243] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted, NSUnderlyingError=0x7f907d6339e0 {Error Domain=com.apple.dtdevicekit Code=-402652994 "App installation failed" UserInfo={NSLocalizedDescription=App installation failed, com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x0000000115c6df4f DTDKCreateNSError + 113
	1   DTDeviceKitBase                     0x0000000115c6e793 DTDK_AMDErrorToNSError + 1135
	2   DTDeviceKitBase                     0x0000000115caf4f1 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 158
	3   DVTFoundation                       0x000000010c182be2 DVTInvokeWithStrongOwnership + 73
	4   DTDeviceKitBase                     0x0000000115caf1af -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1301
	5   IDEiOSSupportCore                   0x0000000115ba50ff __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.340 + 4009
	6   DVTFoundation                       0x000000010c2a5a91 __DVTDispatchAsync_block_invoke + 806
	7   libdispatch.dylib                   0x00007fff7a38d5fa _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff7a385db8 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff7a39a217 _dispatch_queue_serial_drain + 635
	10  libdispatch.dylib                   0x00007fff7a38d166 _dispatch_queue_invoke + 373
	11  libdispatch.dylib                   0x00007fff7a39af0d _dispatch_root_queue_drain_deferred_wlh + 332
	12  libdispatch.dylib                   0x00007fff7a39ed21 _dispatch_workloop_worker_thread + 880
	13  libsystem_pthread.dylib             0x00007fff7a6d6fd2 _pthread_wqthread + 980
	14  libsystem_pthread.dylib             0x00007fff7a6d6be9 start_wqthread + 13
), NSLocalizedRecoverySuggestion=This application’s application-identifier entitlement does not match that of the installed application. These values must match for an upgrade to be allowed., NSLocalizedFailureReason=This application’s application-identifier entitlement does not match that of the installed application. These values must match for an upgrade to be allowed.}}}

Testing failed:
	Early unexpected exit, operation never finished bootstrapping - no restart will be attempted
** TEST FAILED **

**Comment by xiaomingstudy** [comment]
而且比较坑的一个问题，如果这两条命令执行顺序颠倒的话，执行时没问题的。。。。

**Comment by pluie-cloud** [comment]
检查下授信

**Comment by xiaomingstudy** [comment]
@pluie-cloud  授信没问题啊
