### ISSUE TITLE
XCTestWD能否增加支持录制屏幕视频流的功能

### ISSUE THREAD

**Issue by adfghzhang** [macacajs/XCTestWD#135]
XCTestWD和WDA都能支持截图功能，但都不能支持录制屏幕输出视频流。
该功能设想如下：
1.接收用户发起的开始录制请求即启动录制，接收到停止请求时完成录制并输出视频文件，或者在设备端开启一个socket服务输出视频流供外部调用。
2.因目前设备分辨率过高，可考虑支持用户自定义录制视频的分辨率大小减少系统性能开销。
请XCTestWD团队研究一下是否能提供支持。

**Comment by SamuelZhaoY** [comment]
对于模拟器可以直接使用指令 `xcrun simctl io ${booted-device-name} recordVideo ${file-name} ` 进行录制，这个指令建议直接在脚本层自行嵌入. 做了下调研，目前没有发现可以在UITest 中获取到UIKit 窗体模型的方法，欢迎一起讨论交流.
