### ISSUE TITLE
多设备启动XCTestWD服务,第一个使用服务会挂掉

### ISSUE THREAD

**Issue by xinxi1990** [macacajs/XCTestWD#136]
多设备使用XCTestWD已经指明了不同的端口

  Error: connect ECONNREFUSED 127.0.0.1:8902
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1170:14)

**Comment by SamuelZhaoY** [comment]
目前XCTestWD 暂时不支持多设备运行，如果需要改造，可以参考此文章https://medium.com/@t.camin/parallelizing-ui-tests-28c16000f141， 原理是运行时根据设备数量动态创建多target， 并复制模拟器.
