### ISSUE TITLE
ci failed

### ISSUE THREAD

**Issue by xudafeng** [macacajs/XCTestWD#138]
Testing failed:
	Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1.2: /Users/distiller/project/XCTestWD/XCTestWDUnitTest/Swifter.framework/Modules/Swifter.swiftmodule/x86_64.swiftmodule

**Comment by xudafeng** [comment]
https://circleci.com/gh/macacajs/XCTestWD/52

**Comment by SamuelZhaoY** [comment]
https://circleci.com/gh/macacajs/XCTestWD/tree/master fixed
