### ISSUE TITLE
XCTestWD和测试app一直崩溃

### ISSUE THREAD

**Issue by xingtao555** [macacajs/XCTestWD#139]
打开macaca服务，执行uirecorder start --mobile，iOS（模拟器），无法打开XCTestWDUITests和自己的app，一直闪退

**Comment by SamuelZhaoY** [comment]
奔溃日志给一下， 同时能否运行macaca sample

**Comment by xingtao555** [comment]
激动，终于回复了,脚本可以执行，就是录制和nosmoke会出现
2018-09-07 19:36:22.441966+0800 XCTestWDUITests-Runner[30789:948604] XCTestWD-Debug-Info: 
 create bundle from launching input
    t =     0.11s Open com.enterprise.haha.customer
    t =     0.16s     Launch com.enterprise.haha.customer
    t =     2.34s         Assertion Failure: XCTestWDRunner.swift:31: Failed to launch com.enterprise.bianlifeng.customer: The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.)
2018-09-07 19:36:24.782290+0800 XCTestWDUITests-Runner[30789:948581] *** Terminating app due to uncaught exception '_XCTestCaseInterruptionException', reason: 'Interrupting test'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010b1ae1e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010a843031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010b223975 +[NSException raise:format:] + 197
	3   XCTest                              0x000000010a13eba8 -[XCUIApplicationImpl _waitForValidPID] + 176
	4   XCTest                              0x000000010a13cf65 __42-[XCUIApplicationImpl _launchWithRequest:]_block_invoke + 725
	5   XCTest                              0x000000010a13098d -[XCTContext _runActivityNamed:type:block:] + 245
	6   XCTest                              0x000000010a0d2518 -[XCTestCase startActivityWithTitle:type:block:] + 218
	7   XCTest                              0x000000010a0d26f5 -[XCTestCase startActivityWithTitle:block:] + 60
	8   XCTest                              0x000000010a13cc5a -[XCUIApplicationImpl _launchWithRequest:] + 216
	9   XCTest                              0x000000010a13098d -[XCTContext _runActivityNamed:type:block:] + 245
	10  XCTest                              0x000000010a0d2518 -[XCTestCase startActivityWithTitle:type:block:] + 218
	11  XCTest                              0x000000010a0d26f5 -[XCTestCase startActivityWithTitle:block:] + 60
	12  XCTest                              0x000000010a13c838 -[XCUIApplicationImpl serviceOpenRequest:] + 244
	13  XCTest                              0x000000010a103313 -[XCUIApplication _launchUsingXcode:] + 388
	14  XCTestWD                            0x000000012061a594 _T08XCTestWD0A19WDSessionControllerC13createSession7Swifter12HttpResponseOAE0H7RequestC7request_tFZ + 6980
	15  XCTestWD                            0x000000012061d9c0 _T08XCTestWD0A19WDSessionControllerC13createSession7Swifter12HttpResponseOAE0H7RequestC7request_tFZTA + 16
	16  XCTestWD                            0x00000001205f751f _T07Swifter11HttpRequestCAA0B8ResponseOIegxr_AcEIegir_TR + 15
	17  XCTestWD                            0x000000012061b0b1 _T07Swifter11HttpRequestCAA0B8ResponseOIegxr_AcEIegir_TRTA + 17
	18  XCTestWD                            0x00000001205f42d4 _T07Swifter11HttpRequestCAA0B8ResponseOIegir_AcEIegxr_TR + 20
	19  XCTestWD                            0x00000001205f6361 _T07Swifter11HttpRequestCAA0B8ResponseOIegir_AcEIegxr_TRTA + 17
	20  XCTestWD                            0x00000001205f04f4 _T08XCTestWD11RouteOnMain7Swifter12HttpResponseOAC0G7RequestCcAeGcFAeGcfU_yycfU_ + 100
	21  XCTestWD                            0x00000001205f0579 _T08XCTestWD11RouteOnMain7Swifter12HttpResponseOAC0G7RequestCcAeGcFAeGcfU_yycfU_TA + 25
	22  XCTestWD                            0x00000001205effad _T0Ig_IyB_TR + 45
	23  libdispatch.dylib                   0x000000010f9e1709 _dispatch_client_callout + 8
	24  libdispatch.dylib                   0x000000010f9ecbcf _dispatch_sync_thread_bound_invoke + 108
	25  libdispatch.dylib                   0x000000010f9e1709 _dispatch_client_callout + 8
	26  libdispatch.dylib                   0x000000010f9eb708 _dispatch_main_queue_callback_4CF + 1279
	27  CoreFoundation                      0x000000010b170c99 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	28  CoreFoundation                      0x000000010b134ea6 __CFRunLoopRun + 2342
	29  CoreFoundation                      0x000000010b13430b CFRunLoopRunSpecific + 635
	30  Foundation                          0x000000010a23eb4a -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 274
	31  Foundation                          0x000000010a23ea25 -[NSRunLoop(NSRunLoop) run] + 76
	32  XCTestWD                            0x00000001205f1719 _T08XCTestWD0A8WDServerC11startServeryyF + 1881
	33  XCTestWDUITests                     0x0000000120452748 _T015XCTestWDUITests14XCTextWDRunnerC10testRunneryyF + 168
	34  XCTestWDUITests                     0x00000001204527a4 _T015XCTestWDUITests14XCTextWDRunnerC10testRunneryyFTo + 36
	35  CoreFoundation                      0x000000010b131ccc __invoking___ + 140
	36  CoreFoundation                      0x000000010b131b84 -[NSInvocation invoke] + 308
	37  XCTest                              0x000000010a0ca01a __24-[XCTestCase invokeTest]_block_invoke.184 + 74
	38  XCTest                              0x000000010a124ae3 +[XCTestCase(Failures) performFailableBlock:shouldInterruptTest:] + 36
	39  XCTest                              0x000000010a124a2e -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 54
	40  XCTest                              0x000000010a0c9ce3 __24-[XCTestCase invokeTest]_block_invoke + 847
	41  XCTest                              0x000000010a129a7d -[XCUITestContext performInScope:] + 248
	42  XCTest                              0x000000010a0c997f -[XCTestCase invokeTest] + 175
	43  XCTest                              0x000000010a0cb555 __26-[XCTestCase performTest:]_block_invoke_2 + 42
	44  XCTest                              0x000000010a124ae3 +[XCTestCase(Failures) performFailableBlock:shouldInterruptTest:] + 36
	45  XCTest                              0x000000010a124a2e -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 54
	46  XCTest                              0x000000010a0cb402 __26-[XCTestCase performTest:]_block_invoke.318 + 90
	47  XCTest                              0x000000010a131061 +[XCTContext runInContextForTestCase:block:] + 225
	48  XCTest                              0x000000010a0caaff -[XCTestCase performTest:] + 673
	49  XCTest                              0x000000010a10d727 -[XCTest runTest] + 57
	50  XCTest                              0x000000010a0c6341 __27-[XCTestSuite performTest:]_block_invoke + 365
	51  XCTest                              0x000000010a0c5b1d -[XCTestSuite _performProtectedSectionForTest:testSection:] + 55
	52  XCTest                              0x000000010a0c5dde -[XCTestSuite performTest:] + 296
	53  XCTest                              0x000000010a10d727 -[XCTest runTest] + 57
	54  XCTest                              0x000000010a0c6341 __27-[XCTestSuite performTest:]_block_invoke + 365
	55  XCTest                              0x000000010a0c5b1d -[XCTestSuite _performProtectedSectionForTest:testSection:] + 55
	56  XCTest                              0x000000010a0c5dde -[XCTestSuite performTest:] + 296
	57  XCTest                              0x000000010a10d727 -[XCTest runTest] + 57
	58  XCTest                              0x000000010a0c6341 __27-[XCTestSuite performTest:]_block_invoke + 365
	59  XCTest                              0x000000010a0c5b1d -[XCTestSuite _performProtectedSectionForTest:testSection:] + 55
	60  XCTest                              0x000000010a0c5dde -[XCTestSuite performTest:] + 296
	61  XCTest                              0x000000010a10d727 -[XCTest runTest] + 57
	62  XCTest                              0x000000010a13afa6 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 40
	63  XCTest                              0x000000010a0de389 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 594
	64  XCTest                              0x000000010a13adb1 -[XCTTestRunSession runTestsAndReturnError:] + 369
	65  XCTest                              0x000000010a0acc71 -[XCTestDriver runTestsAndReturnError:] + 447
	66  XCTest                              0x000000010a12fbb1 _XCTestMain + 960
	67  XCTestWDUITests-Runner              0x0000000109e2549f _XCTRunnerRunTests + 57
	68  CoreFoundation                      0x000000010b150b0c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	69  CoreFoundation                      0x000000010b1352db __CFRunLoopDoBlocks + 331
	70  CoreFoundation                      0x000000010b134a84 __CFRunLoopRun + 1284
	71  CoreFoundation                      0x000000010b13430b CFRunLoopRunSpecific + 635
	72  GraphicsServices                    0x000000010e4d5a73 GSEventRunModal + 62
	73  UIKit                               0x000000010b62b057 UIApplicationMain + 159
	74  XCTestWDUITests-Runner              0x0000000109e256dc main + 42
	75  libdyld.dylib                       0x000000010fa56955 start + 1
	76  ???                                 0x0000000000000005 0x0 + 5
)
