### ISSUE TITLE
跟新了Xcode版本10.0，显示缺少XctestWD-framework10.0

### ISSUE THREAD

**Issue by leroypus** [macacajs/XCTestWD#140]
您好，我的操作步骤如下：
1.跟新Xcode10.0；
2.删除npde_modules之后npm install
3.运行，显示缺少macaca-ios,打开文件夹有macaca-ios
4.运行，显示缺少XctestWD-framework10.0

具体现象：
1.使用npm install跟新的包缺少macaca-ios以及XctestWD一系列的包；
2.使用ncpm install的node_modules包缺少XctestWD-framework10.0

期待得到您的回复，谢谢

**Comment by liyinchigithub** [comment]
我也有此问题 ,可安装版本没有这个10.0
bogon:~ liyinchi$ npm search xctestwd
NAME                      | DESCRIPTION          | AUTHOR          | DATE       
xctestwd                  | Swift…               | =chun_chan…     | 2018-09-29 
xctestwd-frameworks-94    | xctestwd frameworks… | =xudafeng       | 2018-06-01 
xctestwd-frameworks       | xctestwd frameworks… | =samuel.zhaoy…  | 2018-09-30 
xctestwd-frameworks-9.2   | xctestwd frameworks… | =chun_chan…     | 2018-04-04 
xctestwd-frameworks-93    | xctestwd frameworks… | =samuel.zhaoy…  | 2018-04-04 
xctestwd-frameworks-9.1   | xctestwd frameworks… | =xudafeng…      | 2017-11-20

**Comment by gao2q** [comment]
请问什么时候支持xcode 10？

**Comment by xudafeng** [comment]
已支持，重装即可

https://github.com/macacajs/XCTestWD/pull/143
