### ISSUE TITLE
xcode10版本的问题， 找不到XCElementSnapshot头文件

### ISSUE THREAD

**Issue by turinblueice** [macacajs/XCTestWD#141]
运行xcodebuild -project XCTestWD.xcodeproj -scheme XCTestWDUITests -destination "platform=iOS,name=iOS测试6s" XCTESTWD_PORT=8001 clean test 出现如下错误，查了下是xcode10兼容问题，webdriveragent已经更新到最新xcode能编译通过的版本，XCTestWD还没修正更新。

问题如下

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_XCElementSnapshot", referenced from:
      objc-class-ref in XCTestWDAccessibility.o
      l__CATEGORY_XCElementSnapshot_$_XCTestWDUITestsHq in XCTestWDAccessibility.o
      objc-class-ref in XCTestWDApplicationTree.o
      objc-class-ref in XCTestWDXPath.o
ld: symbol(s) not found for architecture arm64
clang: error
: linker command failed with exit code 1 (use -v to see invocation)

**Comment by turinblueice** [comment]
https://github.com/facebook/WebDriverAgent/issues/968

webdriveragent该问题的issue

**Comment by turinblueice** [comment]
@SamuelZhaoY

**Comment by butterflyingdog** [comment]
@turinblueice   you can get the xcode10 suppored version use the  following command： 
```
git clone git@github.com:butterflyingdog/XCTestWD.git 
git checkout   request
```
I also pull request to macacajs/XCTestWD， wating @SamuelZhaoY to  accept my request

when use carthage to get dependencies, should add --configuration Debug, such as "carthage update --configuration Debug --platform iOS"

**Comment by xudafeng** [comment]
@butterflyingdog 

can you give XCTestWD a pull request?

**Comment by xudafeng** [comment]
https://github.com/macacajs/XCTestWD/pull/142

**Comment by turinblueice** [comment]
> @turinblueice you can get the xcode10 suppored version use the following command：
> 
> ```
> git clone git@github.com:butterflyingdog/XCTestWD.git 
> git checkout   request
> ```
> I also pull request to macacajs/XCTestWD， wating @SamuelZhaoY to accept my request
> 
> when use carthage to get dependencies, should add --configuration Debug, such as "carthage update --configuration Debug --platform iOS"

thx for replying，I'll try soon
