### ISSUE TITLE
 timeout while init   tested program   with code >XCUIApplication(bundleIdentifier: bundleIDtest)

### ISSUE THREAD

**Issue by thylinner** [macacajs/XCTestWD#146]
error log>>>
    t =     0.00s Start Test at 
    t =     0.26s Set Up
    t =    60.48s Assertion Failure: XCTestWDMonkey.swift:21: Unable to update application state promptly for Application 'com.apple.mobilesafari'.
    t =    60.59s Tear Down
Test Case '-[XCTestWDUITests.XCTextWDRunner testRunner]' failed (60.591 seconds).
Test Suite 'XCTextWDRunner' failed at 2018-10-09 10:29:35.873.
	 Executed 1 test, with 1 failure (0 unexpected) in 60.591 (60.593) seconds
Test Suite 'XCTestWDUITests.xctest' failed at 2018-10-09 10:29:35.874.
	 Executed 1 test, with 1 failure (0 unexpected) in 60.591 (60.595) seconds
Test Suite 'All tests' failed at 2018-10-09 10:29:35.875.
	 Executed 1 test, with 1 failure (0 unexpected) in 60.591 (60.598) seconds_
________________
error code >>>
let app :XCUIApplication! = XCUIApplication(bundleIdentifier: bundleIDtest)
________________

download code from fastmonkey.
everything was OK before update Xcode 10.
maybe a configuration error by myself
changed config list>  buildsystem: legacy build system ||| framework search add path:xctautomationsupport ||| setting>bitcode : No

tried to fix it and failed. hope for some help here, thanks

**Comment by bupojung** [comment]
> error log>>>
> t = 0.00s Start Test at
> t = 0.26s Set Up
> t = 60.48s Assertion Failure: XCTestWDMonkey.swift:21: Unable to update application state promptly for Application 'com.apple.mobilesafari'.
> t = 60.59s Tear Down
> Test Case '-[XCTestWDUITests.XCTextWDRunner testRunner]' failed (60.591 seconds).
> Test Suite 'XCTextWDRunner' failed at 2018-10-09 10:29:35.873.
> Executed 1 test, with 1 failure (0 unexpected) in 60.591 (60.593) seconds
> Test Suite 'XCTestWDUITests.xctest' failed at 2018-10-09 10:29:35.874.
> Executed 1 test, with 1 failure (0 unexpected) in 60.591 (60.595) seconds
> Test Suite 'All tests' failed at 2018-10-09 10:29:35.875.
> Executed 1 test, with 1 failure (0 unexpected) in 60.591 (60.598) seconds_
> 
> error code >>>
> let app :XCUIApplication! = XCUIApplication(bundleIdentifier: bundleIDtest)
> 
> download code from fastmonkey.
> everything was OK before update Xcode 10.
> maybe a configuration error by myself
> changed config list> buildsystem: legacy build system ||| framework search add path:xctautomationsupport ||| setting>bitcode : No
> 
> tried to fix it and failed. hope for some help here, thanks

Have the same problem. Need help.

**Comment by SamuelZhaoY** [comment]
@bupojung @thylinner need further information on error description and where the error is located. Please follow the debug manual on the readme page and provide further information

**Comment by thylinner** [comment]
had tried last version of fastmonkey, hav't find any logs...
then try newest XCTestWD.  seem bugs fixed ... for now  log is like that>>>

  0.01s Start Test at 
    t =     0.19s Set Up
    t =     0.21s     Pressing Home button
    t =     2.37s Open com.apple.mobilesafari
    t =     2.50s     Launch com.apple.mobilesafari

New version saikou~
