### ISSUE TITLE
Xcode10.1编译XCTestWD，提示找不到Frameworks

### ISSUE THREAD

**Issue by damengwang** [macacajs/XCTestWD#150]
使用新的app-inspector时，编译xctestwd，提示找不到
app-inspector/node_modules/_xctestwd@1.4.5@xctestwd/XCTestWD/Frameworks'

**Comment by xudafeng** [comment]
@damengwang 是支持的，原因多半是在你的系统上文件转移失败了

**Comment by xudafeng** [comment]
可以看到这行提示吧？

https://github.com/macacajs/XCTestWD/blob/master/scripts/install.js#L93

**Comment by SamuelZhaoY** [comment]
两个方案： 重新安装macaca-ios;  或在macaca-ios 全局安装路径下，node_modules/xctestwd 中使用carthage update
