### ISSUE TITLE
run the test case XCTextWDRunner 是怎么运行呢？

### ISSUE THREAD

**Issue by Chersh-Pan** [macacajs/XCTestWD#152]
刚接触IOS，下载了最新的xcode，看说明运行case XCTextWDRunner ，是应该怎么运行呢？ 右键没有这个选项，然后Product 下面的Run是不可选的。直接点击build的时候选择真机情况下，又直接提示Failed with exit code 1，求指点

**Comment by SamuelZhaoY** [comment]
Run it as a standard UITest target
