### ISSUE TITLE
请问大神，多设备并行运行，有办法实现吗？谢谢

### ISSUE THREAD

**Issue by liurj** [macacajs/XCTestWD#153]
rt

**Comment by SamuelZhaoY** [comment]
有的，安卓这边天然支持多设备运行，iOS 会麻烦点，参考https://medium.com/xcblog/speed-up-ios-ci-using-test-without-building-xctestrun-and-fastlane-a982b0060676， 生成 .xctestrun 文件，直接执行该文件，可支持多设备并发运行

**Comment by liurj** [comment]
@SamuelZhaoY 可能上面问题描述的比较简单，我们项目想使用这个框架搞自动化，现在碰到几个问题（ios真机多设备并发问题，以2台设备为例)
1、如果macaca server启动2个不同的端口，同时运行两个测试脚本时，执行时只有一台设备在跑，先启动的那台设备被停止了，查了下问题，好像是XCTestWD这个不能同时运行，这个该怎么处理呢
2、有可能不同设备上运行的是不同脚本
现在的macaca上可以解决上面问题吗？因刚接触自动化测试这块，麻烦大神尽量描述详细些，谢谢哈
