### ISSUE TITLE
hi，i have a problem

### ISSUE THREAD

**Issue by bjlizelin** [macacajs/XCTestWD#160]
when i Command-line input：
xcodebuild -project XCTestWD.xcodeproj \
           -scheme XCTestWDUITests \
           -destination 'platform=iOS,name=iphone8' \
           XCTESTWD_PORT=8001 \
           clean test	
result：
![image](https://user-images.githubusercontent.com/38234865/61525277-a25fcd00-aa4a-11e9-92c2-1852eff72f10.png)

**Comment by adudurant** [comment]
Pls read the log  carefully，you can make it.

**Comment by bjlizelin** [comment]
> 请仔细阅读日志，你可以做到。


I tried to do it, but still failed, can you tell me more?
