### ISSUE TITLE
install failed at macos 10.14 and xcode 10.1

### ISSUE THREAD

**Issue by zxbu** [macacajs/XCTestWD#170]
![image](https://user-images.githubusercontent.com/32785355/71672230-5adabc80-2db0-11ea-873b-455535009a32.png)

![image](https://user-images.githubusercontent.com/32785355/71672279-7b0a7b80-2db0-11ea-9e62-d12ea9343780.png)

because the `xcrun simctl list devices available` return empty at xcode 10.1

can you tell me the  xcode version of you support ?

**Comment by paradite** [comment]
should be fixed by https://github.com/macacajs/XCTestWD/pull/171. re-open if you still have the same issue.
