### ISSUE TITLE
在Xcode 11.5 运行macaca monkey时提示xctest client exit with code: 65

### ISSUE THREAD

**Issue by alan0508** [macacajs/XCTestWD#175]
怎么解决这个问题：
在Xcode 11.5 运行macaca monkey时提示xctest client exit with code: 65
>> macaca-ios.js:171:12 [master] pid:42232 Trying to start xctestwd server...
>> xctest-client.js:283:14 [master] pid:42232 xcode version: 11.5
>> XCTestWD version: 1.4.24
>> xctest-client.js:230:20 [master] pid:42232 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.4.24@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:42232 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.4.24@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:42232 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.4.24@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:42232 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.4.24@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:322:14 [master] pid:42232 killing runnerProc pid: 42240

**Comment by xudafeng** [comment]
升级新版
