### ISSUE TITLE
error: Building for iOS Simulator, but the linked and embedded framework 

### ISSUE THREAD

**Issue by ganjarpanji** [macacajs/XCTestWD#182]
![image](https://user-images.githubusercontent.com/1736817/102467352-c5007600-4082-11eb-8a76-4301a817bafc.png)
I got those errors above when build using xcodebuild 12.3, find solution here https://stackoverflow.com/a/51205222
by adding one argument `-UseModernBuildSystem=NO` then the build will succeed.

i think this argument should be added to `install.js`

**Comment by paradite** [comment]
published
```
npm notice === Tarball Details ===
npm notice name:          xctestwd
npm notice version:       1.4.28
npm notice package size:  58.3 kB
npm notice unpacked size: 299.8 kB
npm notice shasum:        cef0dbcf4739d54b0fe31c10ac25c42e8490030f
npm notice integrity:     sha512-pkQlWmWi2E1tb[...]BCY13zrY1qIiw==
npm notice total files:   99
npm notice
+ xctestwd@1.4.28
```
