### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by XiaogeWang** [macacajs/XCTestWD#184]
Building for iOS, but the linked and embedded framework 'Swifter.framework' was built for iOS + iOS Simulator.
Building for iOS, but the linked and embedded framework 'SwiftyJSON.framework' was built for iOS + iOS Simulator.
Building for iOS, but the linked and embedded framework 'CocoaLumberjackSwift.framework' was built for iOS + iOS Simulator.
Building for iOS, but the embedded framework 'Fuzi.framework' was built for iOS + iOS Simulator.
Building for iOS, but the linked and embedded framework 'CocoaLumberjack.framework' was built for iOS + iOS Simulator.
Building for iOS, but the embedded framework 'AEXML.framework' was built for iOS + iOS Simulator.

mac os 11.0.1 
xcode 12.3

**Comment by ganjarpanji** [comment]
duplicated https://github.com/macacajs/XCTestWD/issues/182
please update xctestwd using latest version.

**Comment by paradite** [comment]
duplicate of #182 . re-open if error persists
