### ISSUE TITLE
error: no such module 'Swifter'

### ISSUE THREAD

**Issue by liyinchigithub** [macacajs/XCTestWD#190]
xcode 12.5

![image](https://user-images.githubusercontent.com/19643260/126642608-ecd00f4b-5358-404d-8506-1d8ed1e00f4d.png)
![image](https://user-images.githubusercontent.com/19643260/126642653-57e39255-efe7-4e63-aeb1-66cc7f4fdd33.png)

**Comment by tianmeijie** [comment]
我是一样的报错，build会失败

**Comment by paradite** [comment]
fixed in #193 xctestwd@1.4.30, see #191 for more details
