### ISSUE TITLE
xcode12.5 build 成功,但是app-inspector 启动后会抛个错,然后页面上一直在等待设备启动

### ISSUE THREAD

**Issue by FuChen1649** [macacajs/XCTestWD#191]
xcode 版本 12.5

<img width="800" alt="Screen Shot 2021-08-24 at 2 04 54 PM" src="https://user-images.githubusercontent.com/39113750/130564724-0d6129eb-57b9-47f7-8921-eb62307683da.png">

<img width="1198" alt="Screen Shot 2021-08-24 at 2 06 35 PM" src="https://user-images.githubusercontent.com/39113750/130564841-ad821348-354e-4795-8d2e-d186daf4eefc.png">

大佬不修复这个bug。手机只要升级到最新的系统,就都不能用了.xcode12.5以下的版本不支持最新的ios版本了..

**Comment by niyaoyao** [comment]
需要修改 xctest-client.js 中的代码。 单独运行 npm run driver 可以编译成功 XCTestWD.xcodeproj 项目，单步 debug 发现 yeild 等待的方法超时 `const logPath = yield this.startBootstrap(false);` 这是因为 Macaca 设置了 `exports.simulatorLogFlag = 'IDETestOperationsObserverDebug: Writing diagnostic log for test session to:';` 常量，默认 xocde 编译之后会输出 log 存储地址，但 Xcode12.5 之后并没有输出 Log 地址，导致 yeild 超时。

解决办法修改 xctest-client.js 中 else 部分的源码，添加 `resolve(res);` 避免超时。 @FuChen1649 @atian25 @supern @liangjun-jiang 
```
proc.stderr.on('data', data => {
        logger.debug(data);
        if (!xctestrun) {
          logger.info('>>>>>>>>>>>>>>>>>>>>>')
          logger.info(simulatorLogFlag)
          logger.info('<<<<<<<<<<<<<<<<<<<<<')
 
          logger.info('~~~~~~~~~~~~~~~~~~')
          logger.info(data.indexOf(simulatorLogFlag))
          logger.info('~~~~~~~~~~~~~~~~~~')
           if (~data.indexOf(simulatorLogFlag)) {
             const list = data.split(simulatorLogFlag);
            const res =  list[1].trim();
             logger.debug('hitted for default mode');
            resolve(res);
           } else {
             logger.debug(`please check project: ${projectPath}`);
             resolve(res);
           }
        }
      });
```

**Comment by niyaoyao** [comment]
@FuChen1649 建议换技术栈吧，他们官方维护 macaca 还不如我维护地勤。

**Comment by paradite** [comment]
Let me take a look at this issue.

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/999

**Comment by FuChen1649** [comment]
> @FuChen1649 建议换技术栈吧，他们官方维护 macaca 还不如我维护地勤。

有什么好的测试flutter开发的app 的工具推荐吗,没找到合适的才选的macaca

**Comment by paradite** [comment]
![Screenshot 2021-09-15 at 2 31 43 PM](https://user-images.githubusercontent.com/1209810/133382356-7838f008-be8e-45e3-b19d-564f562829d4.png)
@niyaoyao 感谢提供方案，本地已经修复验证通过。马上发布。

**Comment by paradite** [comment]
xctestwd@1.4.30 已发布，问题应该修复了。 @niyaoyao @FuChen1649 

```bash
npm notice === Tarball Details ===
npm notice name:          xctestwd
npm notice version:       1.4.30
npm notice package size:  58.2 kB
npm notice unpacked size: 299.3 kB
npm notice shasum:        e86be771b41066ff34867e98ee2ab5f8c91db969
npm notice integrity:     sha512-7RW86NIZKeKsZ[...]1lhs3WUkz6uOw==
npm notice total files:   98
npm notice
+ xctestwd@1.4.30
```

**Comment by FuChen1649** [comment]
> ![Screenshot 2021-09-15 at 2 31 43 PM](https://user-images.githubusercontent.com/1209810/133382356-7838f008-be8e-45e3-b19d-564f562829d4.png)
> @niyaoyao 感谢提供方案，本地已经修复验证通过。马上发布。

我这执行抛这个错,8001 这个代理端口好像没开启
<img width="1117" alt="Screen Shot 2021-09-15 at 3 55 09 PM" src="https://user-images.githubusercontent.com/39113750/133394836-7bb73950-c632-425e-8ba7-8d130906197c.png">

**Comment by paradite** [comment]
> > ![Screenshot 2021-09-15 at 2 31 43 PM](https://user-images.githubusercontent.com/1209810/133382356-7838f008-be8e-45e3-b19d-564f562829d4.png)
> > @niyaoyao 感谢提供方案，本地已经修复验证通过。马上发布。
> 
> 我这执行抛这个错,8001 这个代理端口好像没开启
> <img alt="Screen Shot 2021-09-15 at 3 55 09 PM" width="1117" src="https://user-images.githubusercontent.com/39113750/133394836-7bb73950-c632-425e-8ba7-8d130906197c.png">

删掉app inspector重新安装一次试试，老的build可能会影响。

**Comment by paradite** [comment]
> > ![Screenshot 2021-09-15 at 2 31 43 PM](https://user-images.githubusercontent.com/1209810/133382356-7838f008-be8e-45e3-b19d-564f562829d4.png)
> > @niyaoyao 感谢提供方案，本地已经修复验证通过。马上发布。
> 
> 我这执行抛这个错,8001 这个代理端口好像没开启
> <img alt="Screen Shot 2021-09-15 at 3 55 09 PM" width="1117" src="https://user-images.githubusercontent.com/39113750/133394836-7bb73950-c632-425e-8ba7-8d130906197c.png">

还是不行的话，可以加个 `--verbose` flag看下哪里有问题。目前已知M1 CPU server会跑不起来，还没有解决。

**Comment by xudafeng** [comment]
@FuChen1649 你的系统版本是多少，cpu架构是什么？

**Comment by FuChen1649** [comment]
@xudafeng  mac 系统macOS Big Sur 11.5.2 xcode12.5 cpu是inter的i7

**Comment by FuChen1649** [comment]
@paradite @xudafeng   重新安装app-inspector还是不行 .
<img width="1675" alt="Screen Shot 2021-09-16 at 1 48 39 PM" src="https://user-images.githubusercontent.com/39113750/133556997-ff7e6c2a-2e2d-4bab-afd7-bb5ee07b445b.png">
 标黄的位置是以前的一个已知问题,得单独去某个分支下载个xctest-cline.js 的脚本才能解决,这个你们好像一直没合到你们master上,我刚替换了试下,不抛iproxy 问题,但打开页面还是显示等待device .

**Comment by paradite** [comment]
@FuChen1649 你说的是 https://github.com/alibaba/macaca/issues/929 里面的 **iOS 真机测试无法开启8001端口** 问题是吧？好的。我看看把这个fix合并进去。

**Comment by FuChen1649** [comment]
@paradite   你本地的xcode 版本多少呢 .我这12.5 .  你要是xcode 版本和我一样 . 你得把下图这个carthage 用你本地的覆盖提交下 .不然别人用会提示swift 版本不对 .. 自己去更新 总是会碰到某个库更新失败...最痛苦
<img width="778" alt="Screen Shot 2021-09-16 at 4 15 11 PM" src="https://user-images.githubusercontent.com/39113750/133576795-56abfecf-3e9e-46bb-9c9f-e4691f945ec3.png">
<img width="558" alt="Screen Shot 2021-09-16 at 4 18 37 PM" src="https://user-images.githubusercontent.com/39113750/133576823-0a3bb8cb-3d7a-49d7-832f-470d18dc2003.png">

**Comment by paradite** [comment]
@FuChen1649 8001 端口问题在 `xctestwd@1.4.31` 应该修复了，重新安装试一下。
```
npm notice name:          xctestwd
npm notice version:       1.4.31
npm notice package size:  58.2 kB
npm notice unpacked size: 299.3 kB
npm notice shasum:        4e40caa44504a4a6002a98f17bdad68c2f36564a
npm notice integrity:     sha512-O0H0YqBcI2Kgn[...]28QS71grnAK+g==
npm notice total files:   98
npm notice
+ xctestwd@1.4.31
```

**Comment by FuChen1649** [comment]
@paradit
<img width="1675" alt="Screen Shot 2021-09-17 at 10 08 23 AM" src="https://user-images.githubusercontent.com/39113750/133712851-ec22a432-ae9f-4b00-915d-eb1e6b6ec43b.png">
e 

粗来了... 谢谢😄
