### ISSUE TITLE
./carthage.sh build 报错 Nimble.xcodeproj

### ISSUE THREAD

**Issue by liyinchigithub** [macacajs/XCTestWD#192]
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/liyinchi/workspace/AutoTest/mobile/nodejs/macaca/XCTestWD/Carthage/Checkouts/Nimble/Nimble.xcodeproj -scheme Nimble-tvOS -configuration Release -derivedDataPath /Users/liyinchi/Library/Caches/org.carthage.CarthageKit/DerivedData/12.5.1_12E507/Nimble/v8.0.1 -sdk appletvsimulator -destination platform=tvOS\ Simulator,id=2D35B2F5-EB17-4C7F-A9A9-19A0C6D7F830 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build VALIDATE_WORKSPACE=NO (launched in /Users/liyinchi/workspace/AutoTest/mobile/nodejs/macaca/XCTestWD/Carthage/Checkouts/Nimble)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/6y/0wk9jll54wd9tzrcpjjk5n1r0000gn/T/carthage-xcodebuild.Qa2ANA.log

**Comment by liyinchigithub** [comment]
carthage version
0.38.0

**Comment by paradite** [comment]
fixed in #193 `xctestwd@1.4.30`, see #191 for more details
