### ISSUE TITLE
Xcode13 build 提示 Swift5.4 cannot be imported by Swift 5.5  compiler:***

### ISSUE THREAD

**Issue by FuChen1649** [macacajs/XCTestWD#199]
xcode 升级到13 ，提示swift 兼容性问题 。 通过Carthage.sh 尝试更新，总是失败。 麻烦官方，重新用xcode 13 build 下。

**Comment by paradite** [comment]
我这里 Carthage bootstrap 也遇到了问题，估计得花点时间看一下。

**Comment by FuChen1649** [comment]
@paradite  thanks
