### ISSUE TITLE
ci pass

### ISSUE THREAD

**Issue by xudafeng** [macacajs/XCTestWD#20]

**Comment by xudafeng** [comment]
https://travis-ci.org/macaca-sample/sample-nodejs/jobs/232019458

**Comment by SamuelZhaoY** [comment]
>> xctest-client.js:175:14 [master] pid:4366 please check project: /Users/travis/build/macaca-sample/sample-nodejs/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:257:14 [master] pid:4366 killing deviceLogProc pid: 4778
>> xctest-client.js:262:14 [master] pid:4366 killing runnerProc pid: 4777
>> xctest-client.js:185:14 [master] pid:4366 xctest client exit with code: 65, signal: null
>> xctest-client.js:109:18 [master] pid:4366 simulator log process exit with code: null, signal: SIGKILL
>> proxy.js:61:22 [master] pid:4366 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:4366 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:4366 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:4366 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:4366 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:4366 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:174:14 [master] pid:4366 Failing tests:
	-[XCTextWDRunner testRunner()]
** TEST FAILED **
>> xctest-client.js:175:14 [master] pid:4366 please check project: /Users/travis/build/macaca-sample/sample-nodejs/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:61:22 [master] pid:4366 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:4366 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:257:14 [master] pid:4366 killing deviceLogProc pid: 4460
>> xctest-client.js:262:14 [master] pid:4366 killing runnerProc pid: 4459
>> xctest-client.js:185:14 [master] pid:4366 xctest client exit with code: 65, signal: null
>> xctest-client.js:109:18 [master] pid:4366 simulator log process exit with code: null, signal: SIGKILL
>> proxy.js:61:22 [master] pid:4366 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:4366 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:4366 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:4366 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:4366 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:249:14 [master] pid:4366 Fail to start xctest: Error: connect ECONNREFUSED 127.0.0.1:8001

从 https://travis-ci.org/macaca-sample/sample-nodejs/jobs/232019458 目前的这段逻辑看，这个case 里的问题是因为启动了多次.  跟昨晚的日志不一样

**Comment by SamuelZhaoY** [comment]
done

**Comment by JudyJia** [comment]
请问这个问题怎么解决？
