### ISSUE TITLE
Run failed

### ISSUE THREAD

**Issue by AppleZou** [macacajs/XCTestWD#26]
Run  the following command  failed on the real device 
$ xcodebuild -project XCTestWD.xcodeproj \
           -scheme XCTestWDUITests \
           -destination 'platform=iOS,name=(your device name)' \
           XCTESTWD_PORT=8001 \
           test

MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/5z/hjq6vzl133sf0kjt5fhv4nb80000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/88c672695bc1db12969cf51fe0fcabdd/43d388600e6a6f0ca35ed991f73ae96eb30f59aa/XCTestWDUITests-Runner.app
state->new_bundle: /Users/apple/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Build/Products/Debug-iphoneos/XCTestWDUITests-Runner.app
state->dst_bundle: /var/folders/5z/hjq6vzl133sf0kjt5fhv4nb80000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.wmQG1t/XCTestWDUITests-Runner.app_sparse.ipa/Payload//XCTestWDUITests-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/5z/hjq6vzl133sf0kjt5fhv4nb80000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.wmQG1t/XCTestWDUITests-Runner.app_sparse.ipa
__MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/5z/hjq6vzl133sf0kjt5fhv4nb80000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.wmQG1t/XCTestWDUITests-Runner.app_sparse.ipa/ManifestCache.plist
writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/5z/hjq6vzl133sf0kjt5fhv4nb80000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.wmQG1t/XCTestWDUITests-Runner.app_sparse.ipa/ManifestCache.plist
2017-05-17 17:33:35.202273+0800 XCTRunner[780:340761] Running tests...
2017-05-17 17:33:36.236875+0800 XCTRunner[780:340799] Connection peer refused channel request for "dtxproxy:XCTestDriverInterface:XCTestManager_IDEInterface"; channel canceled <DTXChannel: 0x170086f40>
2017-05-17 17:33:36.316 xcodebuild[1844:30558] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

Testing failed:
	Test target XCTestWDUITests encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
** TEST FAILED **

@xudafeng

**Comment by adudurant** [comment]
@AppleZou  怎么解决的啊
