### ISSUE TITLE
 Run the test case XCTextWDRunner  failed

### ISSUE THREAD

**Issue by AppleZou** [macacajs/XCTestWD#31]
![image](https://cloud.githubusercontent.com/assets/25732354/26235786/a556207e-3c9f-11e7-861f-253e4643cc39.png)

![image](https://cloud.githubusercontent.com/assets/25732354/26235825/d187c4b8-3c9f-11e7-9c14-c92ba5f01dc1.png)

@xudafeng

**Comment by xudafeng** [comment]
npm i macaca-cli -g && macaca doctor

**Comment by AppleZou** [comment]
@xudafeng 
According to you said to run command npm i macaca-cli -g && macaca doctor,still haven't solve.
![image](https://cloud.githubusercontent.com/assets/25732354/26272653/bbc4541e-3d50-11e7-860d-e14de814d08a.png)

**Comment by SamuelZhaoY** [comment]
@AppleZou update your node to 6.9.2+.  For running on real devices, please ensure you have configure XCode developer certificate and install the corresponding provisioning profile on iOS target devices

**Comment by AppleZou** [comment]
@SamuelZhaoY Thanks,i ensure i have configure XCode developer certificate and install the corresponding provisioning profile on iOS target devices, i update node version,can build successfully,but i run command "
xcodebuild -project XCTestWD.xcodeproj \
           -scheme XCTestWDUITests \
           -destination 'platform=iOS,name=iPhone' \
           XCTESTWD_PORT=8001 \
           test"
show the follwing failed log.
![image](https://cloud.githubusercontent.com/assets/25732354/26280407/00688b76-3e05-11e7-981e-0009770a5993.png)
In addition,i run app-inspector show failed log is the following:
![image](https://cloud.githubusercontent.com/assets/25732354/26280422/a8b8ba9e-3e05-11e7-9083-5df8fb3ed77c.png)

**Comment by xudafeng** [comment]
```
DEVELOPMENT_TEAM_ID=TEAM_ID cnpm i app-inspector -g
```

https://testerhome.com/topics/6503

**Comment by AppleZou** [comment]
@xudafeng When i run  DEVELOPMENT_TEAM_ID=TEAM_ID cnpm i app-inspector -g,show the follwing error:
![image](https://cloud.githubusercontent.com/assets/25732354/26282401/6d581c7c-3e43-11e7-891a-060876b9aefa.png)

**Comment by xudafeng** [comment]
because of android environment error, optional warning.

**Comment by AppleZou** [comment]
Oh,my god,i didn't know why show build failed again,i only run command "DEVELOPMENT_TEAM_ID=TEAM_ID npm i app-inspector -g" then to run testRunner()
![image](https://cloud.githubusercontent.com/assets/25732354/26285152/9841aa96-3e7c-11e7-8d41-238a4da8c194.png)
macaca doctor
![image](https://cloud.githubusercontent.com/assets/25732354/26285161/c3e841d2-3e7c-11e7-9122-8c31deaa542d.png)
@xudafeng @SamuelZhaoY

**Comment by AppleZou** [comment]
I run command "app-inspector -u 43d388600e6a6f0ca35ed991f73ae96eb30f59aa --verbose
" show the following error:
![image](https://cloud.githubusercontent.com/assets/25732354/26290917/9156f22a-3edd-11e7-9d56-cb493f62a3b7.png)

![image](https://cloud.githubusercontent.com/assets/25732354/26290924/9b897cc2-3edd-11e7-8b43-db1eb9fb35d5.png)

**Comment by xudafeng** [comment]
@AppleZou check your localhost

**Comment by AppleZou** [comment]
@xudafeng I don't understand what's you meaning,check my localhost refers to check what kind of things.
