### ISSUE TITLE
问下这个是什么问题？

### ISSUE THREAD

**Issue by RmondJone** [macacajs/XCTestWD#42]
>> xctest-client.js:173:14 [master] pid:13005 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:13005 
Testing failed:
	'XCUIApplication' is only available on iOS 9.0 or newer
	'XCUIElement' is only available on iOS 9.0 or newer
	'XCUIApplication' is only available on iOS 9.0 or newer
	'XCUIApplication' is only available on iOS 9.0 or newer
	'XCUIApplication' is only available on iOS 9.0 or newer
	'XCUIElement' is only available on iOS 9.0 or newer
	'XCUIElementType' is only available on iOS 9.0 or newer
	'XCUIElement' is only available on iOS 9.0 or newer
	'XCUIElementType' is only available on iOS 9.0 or newer
	'elementType' is only available on iOS 9.0 or newer
	'XCUIElementType' is only available on iOS 9.0 or newer
	'XCUIElement' is only available on iOS 9.0 or newer
	'XCUIElementType' is only available on iOS 9.0 or newer
	'elementType' is only available on iOS 9.0 or newer
	'alerts' is only available on iOS 9.0 or newer
	'sheets' is only available on iOS 9.0 or newer
	'XCUIElementType' is only available on iOS 9.0 or newer
	'XCUIElementType' is only available on iOS 9.0 or newer
	'elementType' is only available on iOS 9.0 or newer
	'XCUIApplication' is only available on iOS 9.0 or newer
** TEST FAILED **

The following build commands failed:
	CompileSwift normal armv7 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/server/models/XCTestWDStatus.swift
	CompileSwift normal armv7 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/Server/Controllers/XCTestWDStatusController.swift
	CompileSwift normal armv7 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/Server/Controllers/XCTestWDKeysController.swift
	CompileSwift normal armv7 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/Server/Controllers/XCTestWDWindowController.swift
	CompileSwift normal armv7 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/server/models/XCTestWDAlert.swift
	CompileSwift normal armv7 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/Server/Controllers/XCTestWDScreenshotController.swift
	CompileSwift normal armv7 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/server/models/extensions/XCTestWDApplicationTree.swift
	CompileSwift normal armv7 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/Server/XCTestWDServer.swift
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
(9 failures)

>> xctest-client.js:173:14 [master] pid:13005 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:255:14 [master] pid:13005 killing deviceLogProc pid: 13008
>> xctest-client.js:260:14 [master] pid:13005 killing runnerProc pid: 13011
>> xctest-client.js:266:14 [master] pid:13005 killing iproxyProc pid: 13010
>> xctest-client.js:183:14 [master] pid:13005 xctest client exit with code: 65, signal: null
>> xctest-client.js:211:14 [master] pid:13005 iproxy exit with code: null, signal: SIGKILL
>> xctest-client.js:145:16 [master] pid:13005 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:247:14 [master] pid:13005 Fail to start xctest: undefined
undefined
>> iOS device started: 327148b379e10cad789f12bd457b76018fd0eeca
>> inspector start at: http://172.32.145.105:5678
  <-- GET /
>> helper.js:94:16 [master] pid:13005 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1050:11)
      at exports._exceptionWithHostPort (util.js:1073:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)

**Comment by RmondJone** [comment]
设备是5C,IOS 10.3，Xcode版本是8.3.2,应该是最新的了吧，有时候就行，有的时候就不行，有的时候重启一下设备就好了，有的时候重启设备还是没用。

**Comment by SamuelZhaoY** [comment]
没看懂你第一段log 跟第二段的联系， 第一段应该是你编译选择了 iOS9 一下的模拟器.  第二段是运行以后发生的， 可以断点看一下哪里出问题了
