### ISSUE TITLE
项目编译不过去

### ISSUE THREAD

**Issue by sdlbp** [macacajs/XCTestWD#51]
![image](https://user-images.githubusercontent.com/16012134/27464425-05abf626-5800-11e7-9f83-e48eae5eb46f.png)
如图所示

**Comment by sdlbp** [comment]
如上图所示

**Comment by SamuelZhaoY** [comment]
请给更详细信息

**Comment by sdlbp** [comment]
git clong 下项目后后尝试编译 就出现这个情况

**Comment by SamuelZhaoY** [comment]
给一下错误日志
