### ISSUE TITLE
Test target XCTestWDUITests encountered an error (No Info.plist found for application at path

### ISSUE THREAD

**Issue by askeledz** [macacajs/XCTestWD#53]
Test target XCTestWDUITests encountered an error (No Info.plist found for application at path /Users/askeledzija/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Build/Products/Debug-iphonesimulator/XCTestWD.app/Info.plist If you believe this error represents a bug, please attach the log file at /Users/askeledzija/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/DD3B81A2-20F2-48D1-81B6-50A0346365BB/Session-XCTestWDUITests-2017-06-25_074436-Ba88RN.log)
** TEST FAILED **

**Comment by 1214503056** [comment]
请问这个问题解决了吗？我今天遇到了，求解决方案！谢谢
