### ISSUE TITLE
macaca支持跨应用吗？比如测试调用拨号、通讯录、设置等系统应用

### ISSUE THREAD

**Issue by xray2008** [macacajs/XCTestWD#57]
比如我想退出app，调起系统拨号功能，看拨号是否对后台的被测app是否有影响。
这种操作如何实现？@SamuelZhaoY

**Comment by SamuelZhaoY** [comment]
目前不支持，macaca 目前设计围绕单个活跃app 进行交互， 使用home 操作后， app 转台变换， session 对应的app 不再处于active 状态， 进行操作会导致测试脚本异常， 需要根据切回后台场景改造优化当前实现.

**Comment by SamuelZhaoY** [comment]
@xray2008  已经支持 ，请在 7月 31号更新最新版本

**Comment by SamuelZhaoY** [comment]
按照最新版本的内部设计， macaca xctestwd 可以在app 内外获取元素， 并且不会导致 socket hangup
