### ISSUE TITLE
driver.sendkeys() 无法输入

### ISSUE THREAD

**Issue by mengdg** [macacajs/XCTestWD#58]
.1:8901/wd/hub/session/4CEE78CD-98BC-4E99-B270-54A86070D9A6/screenshot:GET with body: 
>> proxy.js:83:20 [master] pid:2436 Got response with status 200: {"sessionId":"9f3c7a9f-e57b-4466-97b9-3770c6541485","status":0,"value":"iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAAAXNSR0IArs4c6QAAABxpRE9UAAAAAgAAAAAAAAKbAAAAKAAAApsAAAKbAABiRz7W/NsAAEAASURBV...
>> responseHandler.js:47:14 [master] pid:2436 Send HTTP Respone to Client[2017-07-14 11:53:35]: {"sessionId":"9f3c7a9f-e57b-4466-97b9-3770c6541485","status":0,"value":"\"iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAAAXNSR0IArs4c6QAAABxpRE9UAAAAAgAAAAAAAAKbAAAAKAAAApsAAAKbAABiRz7W/NsAAEAASURBVHgB7N2HmztXeTZg/sB8pFFCJ4BDNb2ZZtMJzQEC2IBx6MWhm95LQgm9OYYYU4wbYIy7MTDfPDu8v52dHWm1XWf3nuvSSqsyOrrPK80zozOju/3zo7rOiYEaUANqQA2oATWgBtSAGljvGribDlrvDtI/+kcNqAE1oAbUgBpQA2ogNSC4+8bBNy5qQA2oATWgBtSAGlADDdSA4N5AJ1nLtpatBtSAGlADakANqAE1ILgL7taw1YAaUANqQA2oATWgBhqoAcG9gU6yhm0N..."}
>> responseHandler.js:11:12 [master] pid:2436 Recieve HTTP Request from Client[2017-07-14 11:53:35]: method: GET url: /wd/hub/session/9f3c7a9f-e57b-4466-97b9-3770c6541485/screenshot, jsonBody: {}
>> proxy.js:55:14 [master] pid:2436 Proxy: /wd/hub/session/9f3c7a9f-e57b-4466-97b9-3770c6541485/screenshot:GET to http://127.0.0.1:8901/wd/hub/session/4CEE78CD-98BC-4E99-B270-54A86070D9A6/screenshot:GET with body: 
>> proxy.js:83:20 [master] pid:2436 Got response with status 200: {"sessionId":"9f3c7a9f-e57b-4466-97b9-3770c6541485","status":0,"value":"iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAAAXNSR0IArs4c6QAAABxpRE9UAAAAAgAAAAAAAAKbAAAAKAAAApsAAAKbAABhacktotcAAEAASURBV...
>> responseHandler.js:47:14 [master] pid:2436 Send HTTP Respone to Client[2017-07-14 11:53:35]: {"sessionId":"9f3c7a9f-e57b-4466-97b9-3770c6541485","status":0,"value":"\"iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAAAXNSR0IArs4c6QAAABxpRE9UAAAAAgAAAAAAAAKbAAAAKAAAApsAAAKbAABhacktotcAAEAASURBVHgB7N2HvzRXXT9w/kB/VhQpNjBSg4C0IJBQBESKgmCihEgRhUiTgHQUVEDpLQKGUNOAAOkh4vnN5w7fPPPMnd27tz577n3P67V3926ZPfs+3935zOyZ2Qf83mNac2KgBtSAGlADakANqAE1oAa2uwYeoIO2u4P0j/5RA2pADagBNaAG1IAaSA0I7r5x8I2LGlADakANqAE1oAbUQAc1ILh30EnWsq1lqwE1oAbUgBpQA2pADQjugrs1bDWgBtSAGlADakANqIEOakBw..."}
>> responseHandler.js:11:12 [master] pid:2436 Recieve HTTP Request from Client[2017-07-14 11:53:35]: method: POST url: /wd/hub/session, jsonBody: {"session_id":"9f3c7a9f-e57b-4466-97b9-3770c6541485","desiredCapabilities":{"proxyPort":8900,"deviceName":"孟德功的iPhone","reuse":3,"udid":"053288d1e59d03a3802b90237f01d53cc0d4378b","platformVersion":"10.3.2","platformName":"iOS","bundleId":"com.blued.international"}}
>> session.js:47:10 [master] pid:2436 Creating session, sessionId: f0e3c467-84d4-4b32-b364-626e57a8b159.
>> macaca-ios.js:245:12 [master] pid:2436 App "com.blued.international" is already installed.
>> xctest-client.js:52:14 [master] pid:2436 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> macaca-ios.js:159:10 [master] pid:2436 {
	"bundleId": "com.blued.international",
	"platformVersion": "10.3.2",
	"platformName": "iOS"
}
BundleId XCTestWD.XCTestWD does not exist.

**Comment by SamuelZhaoY** [comment]
请发完整日志

**Comment by SamuelZhaoY** [comment]
使用特定的clearText 指令对文本进行clear， sendKeys 目前接受一般的 键盘文本输入
