### ISSUE TITLE
使用macaca-ios2.0.22,第一条用例执行完，调用driver.quit()后重新initDriver报Error: socket hang up,自动重试后又能连上。

### ISSUE THREAD

**Issue by zsmjluo** [macacajs/XCTestWD#60]
使用macaca-ios2.0.22,第一条用例执行完，调用driver.quit()后重新initDriver报Error: socket hang up,自动重试后又能连上。_**每次执行下一条用例都如此。**_
  
Installed driver list:
  ios: 2.0.22

>> responseHandler.js:11:12 [master] pid:2665 Recieve HTTP Request from Client[2017-07-26 11:36:34]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"reuse":3,"bundleId":"--------","autoDismissAlerts":false,"platformName":"ios","udid":"------a8a81370713ae89653a93877474------","autoAcceptAlerts":false}}
>> session.js:47:10 [master] pid:2665 Creating session, sessionId: 12252da6-4760-42ba-b799-f18d29a7f32f.
>> xctest-client.js:183:14 [master] pid:2665 xctest client exit with code: null, signal: SIGKILL
>> macaca-ios.js:245:12 [master] pid:2665 App "cn.kuaipan.kuaipanIphone" is already installed.
>> xctest-client.js:52:14 [master] pid:2665 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> macaca-ios.js:159:10 [master] pid:2665 {
	"bundleId": "--------",
	"platformName": "ios"
}
BundleId XCTestWD.XCTestWD does not exist.
>> macaca-ios.js:166:12 [master] pid:2665 Trying to start xctestwd server...
>> xctestwd start with port: 8001
>> xctest-client.js:224:14 [master] pid:2665 xcode version: 8.3.3
>> XCTestWD version: 1.1.0
>> xctest-client.js:172:14 [master] pid:2665 2017-07-26 11:36:35.852 xcodebuild[3537:137978]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/xunlei/Library/Developer/Xcode/DerivedData/XCTestWD-csksfttfbygcrbamoobfasiylmgb/Logs/Test/F1E91320-DE33-4012-B884-EC4BBA02860B/Session-XCTestWDUITests-2017-07-26_113635-vDMLsN.log

>> xctest-client.js:173:14 [master] pid:2665 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:2665 2017-07-26 11:36:35.854 xcodebuild[3537:137919] [MT] IDETestOperationsObserverDebug: (50058D3C-F178-4318-BBBF-AF5C6A6B04E7) Beginning test session XCTestWDUITests-50058D3C-F178-4318-BBBF-AF5C6A6B04E7 at 2017-07-26 11:36:35.853 with Xcode 8E3004b on target <DVTiOSDevice: 0x7ff6136c6910> {
		deviceSerialNumber:         F18SQ8JHHG70
		identifier:                 5fe4946a8a81370713ae89653a93877474774c78
		deviceClass:                iPhone
		deviceName:                 XLMP1111
		deviceIdentifier:           5fe4946a8a81370713ae89653a93877474774c78
		productVersion:             10.3.2
		buildVersion:               14F89
		deviceSoftwareVersion:      10.3.2 (14F89)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        28308307968
		deviceAvailableCapacity:    22480809984
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7ff6135cd210 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		} (10.3.2 (14F89))

>> xctest-client.js:173:14 [master] pid:2665 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:2665 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/q4/2skydwf51sv1g0l4ht4rtnvh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/9814b5154cce5d5f1fbd040cf09439e4/5fe4946a8a81370713ae89653a93877474774c78/ManifestCache.plist

>> xctest-client.js:173:14 [master] pid:2665 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:55:14 [master] pid:2665 Proxy: /wd/hub/session:POST to http://127.0.0.1:8001/wd/hub/session:POST with body: {"desiredCapabilities":{"bundleId":"--------","platformName":"ios"}}
# **>> proxy.js:61:22 [master] pid:2665 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2665 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2665 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2665 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2665 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2665 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2665 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2665 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2665 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2665 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2665 xctest client proxy error with: Error: socket hang up**
>> xctest-client.js:247:14 [master] pid:2665 Fail to start xctest: Error: socket hang up
>> xctest-client.js:255:14 [master] pid:2665 killing deviceLogProc pid: 3534
>> xctest-client.js:260:14 [master] pid:2665 killing runnerProc pid: 3537
>> xctest-client.js:266:14 [master] pid:2665 killing iproxyProc pid: 3536
>> xctest-client.js:145:16 [master] pid:2665 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:211:14 [master] pid:2665 iproxy exit with code: null, signal: SIGKILL
>> xctest-client.js:183:14 [master] pid:2665 xctest client exit with code: null, signal: SIGKILL
>> macaca-ios.js:166:12 [master] pid:2665 Trying to start xctestwd server...
>> xctestwd start with port: 8001
>> xctest-client.js:224:14 [master] pid:2665 xcode version: 8.3.3
>> XCTestWD version: 1.1.0
>> xctest-client.js:172:14 [master] pid:2665 2017-07-26 11:37:36.856 xcodebuild[3700:139154]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/xunlei/Library/Developer/Xcode/DerivedData/XCTestWD-csksfttfbygcrbamoobfasiylmgb/Logs/Test/3C50F9B4-9591-49D5-84BD-24754CBC1B34/Session-XCTestWDUITests-2017-07-26_113736-rThe2g.log

>> xctest-client.js:173:14 [master] pid:2665 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:2665 2017-07-26 11:37:36.856 xcodebuild[3700:139153] [MT] IDETestOperationsObserverDebug: (326DFD57-07C8-407D-ACAF-4A710B4AFDFC) Beginning test session XCTestWDUITests-326DFD57-07C8-407D-ACAF-4A710B4AFDFC at 2017-07-26 11:37:36.856 with Xcode 8E3004b on target <DVTiOSDevice: 0x7faef72259d0> {
		deviceSerialNumber:         F18SQ8JHHG70
		identifier:                 5fe4946a8a81370713ae89653a93877474774c78
		deviceClass:                iPhone
		deviceName:                 XLMP1111
		deviceIdentifier:           5fe4946a8a81370713ae89653a93877474774c78
		productVersion:             10.3.2
		buildVersion:               14F89
		deviceSoftwareVersion:      10.3.2 (14F89)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        28308307968
		deviceAvailableCapacity:    22480244736
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7faef47f2c80 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		} (10.3.2 (14F89))

>> xctest-client.js:173:14 [master] pid:2665 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj

**Comment by SamuelZhaoY** [comment]
macaca server --verbose 看一下macaca server 这边运行什么指令报错了 谢谢

**Comment by zsmjluo** [comment]
重新执行initDriver
http://127.0.0.1:8001/wd/hub/session:POST with body: {"desiredCapabilities":{"bundleId":"--------","platformName":"ios"}}
>> proxy.js:61:22 [master] pid:2665 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2665 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2665 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2665 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2665 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2665 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2665 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2665 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2665 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2665 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2665 xctest client proxy error with: Error: socket hang up**
>> xctest-client.js:247:14 [master] pid:2665 Fail to start xctest: Error: socket hang up
>> xctest-client.js:255:14 [master] pid:2665 killing deviceLogProc pid: 3534
>> xctest-client.js:260:14 [master] pid:2665 killing runnerProc pid: 3537
>> xctest-client.js:266:14 [master] pid:2665 killing iproxyProc pid: 3536
>> xctest-client.js:145:16 [master] pid:2665 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:211:14 [master] pid:2665 iproxy exit with code: null, signal: SIGKILL
>> xctest-client.js:183:14 [master] pid:2665 xctest client exit with code: null, signal: SIGKILL
>> macaca-ios.js:166:12 [master] pid:2665 Trying to start xctestwd server...

**Comment by SamuelZhaoY** [comment]
此前 执行了什么命令？

试试： 
xcodebuild -project XCTestWD.xcodeproj \
           -scheme XCTestWDUITests \
           -destination 'platform=iOS Simulator,name=iPhone 6' \
           XCTESTWD_PORT=8001 \
           clean test  

看能否正常启动XCTestWD ， 参考项目 README.MD 中提示进行排查

**Comment by adudurant** [comment]
@SamuelZhaoY  这样执行有用吗？
