### ISSUE TITLE
对于异步加载的页面，高概率找不到较晚时机才加载的元素，需要手动source()一下

### ISSUE THREAD

**Issue by holylousie** [macacajs/XCTestWD#61]
考虑一个场景：执行完一个click，会进入某一页面，假设该页面性能较差，那么该页面会加载较慢；与此同时，XCTestWD底层会创建好一个上下文，后续的元素查找操作就基于这个上下文，一次找不到就再找一次，直到超时，其实前几次找不到后续就不可能再找到了，因为上下文一直没有更新，就会导致明明元素存在，但是死活找不到的情况。

解决办法1（写脚本临时用）：遇到用app-inspector明明能找到的元素在脚本执行时找不到的情况，可以考虑在click后sleep 3-5秒，然后再显式的调用一下source()方法

建议解决办法（@作者）：对于同一个元素查找次数超过5次，就更新一下查找的上下文再进行查找

**Comment by SamuelZhaoY** [comment]
已支持
