### ISSUE TITLE
socket hang up

### ISSUE THREAD

**Issue by chenqb** [macacajs/XCTestWD#63]
>> xctest-client.js:173:14 [master] pid:11855 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/.1.1.2@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:61:22 [master] pid:11855 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:11855 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:11855 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:11855 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:11855 xctest client proxy error with: Error: socket hang up
>> xctest-client.js:172:14 [master] pid:11855 Failing tests:
	-[XCTextWDRunner testRunner()]

>> xctest-client.js:173:14 [master] pid:11855 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/.1.1.2@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:11855 	-[XCTextWDRunner testRunner()]
** TEST FAILED **

>> xctest-client.js:173:14 [master] pid:11855 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/.1.1.2@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:255:14 [master] pid:11855 killing deviceLogProc pid: 11865
>> xctest-client.js:260:14 [master] pid:11855 killing runnerProc pid: 11868
>> xctest-client.js:266:14 [master] pid:11855 killing iproxyProc pid: 11867
>> xctest-client.js:183:14 [master] pid:11855 xctest client exit with code: 65, signal: null
>> xctest-client.js:145:16 [master] pid:11855 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:211:14 [master] pid:11855 iproxy exit with code: null, signal: SIGKILL
>> proxy.js:61:22 [master] pid:11855 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:11855 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> responseHandler.js:54:12 [master] pid:11855 Send Error Respone to Client: Error: connect ECONNREFUSED 127.0.0.1:8001
>> responseHandler.js:60:14 [master] pid:11855 Error: connect ECONNREFUSED 127.0.0.1:8001
    at Object.exports._errnoException (util.js:1023:11)
    at exports._exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1023:11)
      at exports._exceptionWithHostPort (util.js:1046:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

**Comment by SamuelZhaoY** [comment]
此前 执行了什么命令？

试试： 
xcodebuild -project XCTestWD.xcodeproj \
           -scheme XCTestWDUITests \
           -destination 'platform=iOS Simulator,name=iPhone 6' \
           XCTESTWD_PORT=8001 \
           clean test  

看能否正常启动XCTestWD ， 参考项目 README.MD 中提示进行排查

**Comment by adudurant** [comment]
最后得到的结果是什么

**Comment by SamuelZhaoY** [comment]
已修复

**Comment by chenqb** [comment]
如果跳出了应用，再回来，还是socket hang up
