### ISSUE TITLE
python版，IOS应用上的H5页面输入框无法输入

### ISSUE THREAD

**Issue by damengwang** [macacajs/XCTestWD#64]
ios驱动更新到： ios: 2.0.23
测试机：iphone7 plus
语言：python
H5页面选择输入框，进行sendkeys，实际上已经选中控件了，有光标，但是还是没有输入，且提示控件无法选择
出错代码
d.wait_for_element_by_xpath(cfg.get('bid', 'amount')).sendkeys('1000')
选择控件属性：TextField
错误提示：WebDriverError.ELEMENT_IS_NOT_SELECTABLE

之前用wda驱动的时候是可以正常使用的，换了xctestwd后出现此问题

**Comment by xudafeng** [comment]
已fix
