### ISSUE TITLE
ios的录制很不稳定

### ISSUE THREAD

**Issue by adudurant** [macacajs/XCTestWD#68]
ios的录制很不稳定
>> proxy.js:61:22 [master] pid:1070 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8003  
录制的时候经常在服务端报这个错误或者socked hang up  
着急啊

**Comment by SamuelZhaoY** [comment]
已修复

**Comment by adudurant** [comment]
大神给力
