### ISSUE TITLE
频繁获取布局和截图手机会重启

### ISSUE THREAD

**Issue by wangzi1325** [macacajs/XCTestWD#69]
设备：iPhone 6s 64g     iOS.10.3.3

问题： 目前一秒间隔去刷新布局及截图   十几分钟至半个小时左右手机会重启

![image](https://user-images.githubusercontent.com/4196935/29159958-04b5bf0a-7de3-11e7-8ce7-818d7de918e9.png)

**Comment by adudurant** [comment]
确实是这样 ，求解决

**Comment by adudurant** [comment]
这个要在uirecorde端  修改刷新获取屏幕的频率
