### ISSUE TITLE
XCTestWD 可不可以把两个应用合成一个呢 这样比较占用bundleId id资源呀

### ISSUE THREAD

**Issue by pluie-cloud** [macacajs/XCTestWD#75]
XCTestWD 可不可以把两个应用合成一个呢 这样比较占用bundleId id资源呀

**Comment by SamuelZhaoY** [comment]
哪两个应用？ 现在只有xctestwd 以及 测试目标app

**Comment by pluie-cloud** [comment]
@SamuelZhaoY  一个是XCTestWD 和XCTestWDUITests

**Comment by SamuelZhaoY** [comment]
实际上只有 XCTestWDUITests 会安装, 为毛会占用bundleID 资源？ XCTestWD 不需要安装
