### ISSUE TITLE
XCTestWD有办法脱离Xcode弄成一个单独的App来使用吗？

### ISSUE THREAD

**Issue by lancelot9527** [macacajs/XCTestWD#77]

**Comment by SamuelZhaoY** [comment]
欢迎提供方案， XCTestWD 是一组标准的测试用例程序，安装需要 Xcode 指令

**Comment by pluie-cloud** [comment]
那你先得解决第一个问题就是 如何让这个App在后台运行

**Comment by xudafeng** [comment]
编译成可执行文件如何

**Comment by SamuelZhaoY** [comment]
“那你先得解决第一个问题就是 如何让这个App在后台运行”  测试过程中本来就在后台运行....
"编译成系统可执行文件如何"  想了想， 如果出包，反而不方便调试， 而且XCUItest 本来就跟xcode 深度集成的, 保留二进制比较干净，但意义不大
