### ISSUE TITLE
在调用homeScreen这个方法后再次调用元素点击 XCTextWDTests会报错断开连接

### ISSUE THREAD

**Issue by pluie-cloud** [macacajs/XCTestWD#80]
在调用homeScreen这个方法后，再次调用元素点击click  这时命令行XCTextWDTests会报错断开连接
 Terminating app due to uncaught exception '_XCTestCaseInterruptionException', reason: 'Interrupting test'

**Comment by SamuelZhaoY** [comment]
home 之后麻烦试一下source().  因为之前app 已经不活跃了， 需要刷新默认app 对象

**Comment by pluie-cloud** [comment]
@SamuelZhaoY 
 是这个 /wd/hub/session/:sessionId/source 么？

**Comment by pluie-cloud** [comment]
@SamuelZhaoY  homepage 之后调用了下 /wd/hub/session/:sessionId/source 发现还是不行 XCTextWDTests断开连接
Restarting after unexpected exit or crash in XCTextWDRunner/testRunner(); summary will include totals from previous launches.

**Comment by SamuelZhaoY** [comment]
嗯 那有可能是本身tap的保护， 现在 element.tap 这个操作可能会crash 你试试 touch 坐标先.  在考虑把tap  行为换成 坐标的方式实现

**Comment by pluie-cloud** [comment]
@SamuelZhaoY  我只找到了个 touchAndHold 这个我现在调用tap的时候 是tap的坐标 我把elementId置为null

**Comment by pluie-cloud** [comment]
@SamuelZhaoY  这个问题木有解决呀 现在很急 有木有解决的办法呢
我调用homepage之后 重新createsession了也不行
求救

**Comment by adudurant** [comment]
@pluie-cloud  你用wda的tap先试试

**Comment by pluie-cloud** [comment]
@adudurant  但是大神 我现在用得是XCTestWD WDA这么操作是没有问题 请问XCTestWD解决了 麻烦告知下 谢谢
