### ISSUE TITLE
getsession和click不能同时运行 

### ISSUE THREAD

**Issue by pluie-cloud** [macacajs/XCTestWD#82]
启动两个线程同时访问getsession和click 两者的执行时间一个是2.1s一个是2.2s
单独执行getsession时间是20ms click是2.2s  是不是线程同步的时候加锁了呢

**Comment by SamuelZhaoY** [comment]
嗯 枷锁了， 操作在一个设备上的驱动程式是线性的， 也需要线性

**Comment by pluie-cloud** [comment]
@SamuelZhaoY  我看了下webdriberagent 好像是可以同时操作

**Comment by wangzi1325** [comment]
@SamuelZhaoY   这个意思是  source   和 click  两个不能同时进行了吧？

**Comment by pluie-cloud** [comment]
@SamuelZhaoY 感觉在不使用app的会话做操作 很容易就宕掉了 其实这个锁可以不用加的 fb 做的wda就没做这方面的限制

**Comment by SamuelZhaoY** [comment]
app 宕掉目前主要原因是因为底层测试库使用了XCTestAssert， 对于一些场景下接口调用内部会自动判为失败，iOS这端UI测试普遍存在此类问题，这个跟fd 是一样的, 跟加不加锁没关系
