### ISSUE TITLE
XCtestWD存在内存泄漏   排查

### ISSUE THREAD

**Issue by adudurant** [macacajs/XCTestWD#86]

**Comment by SamuelZhaoY** [comment]
![image](https://user-images.githubusercontent.com/8198256/30794446-a8215a56-a1fa-11e7-930f-055321e730e7.png)

内存无泄漏问题， source 流程中代码效率待优化， 
![image](https://user-images.githubusercontent.com/8198256/30794469-bd9ae190-a1fa-11e7-9fd5-58dff1986afe.png)

**Comment by adudurant** [comment]
嗯，验证没问题，可能场景有问题，或有待复现。

**Comment by SamuelZhaoY** [comment]
@adudurant

**Comment by adudurant** [comment]
看看效率这块有没优化的地方
