### ISSUE TITLE
xcode9 版本升级

### ISSUE THREAD

**Issue by SamuelZhaoY** [macacajs/XCTestWD#88]
适配xcode 9， 支持新版本xcodebuild 工具

**Comment by SamuelZhaoY** [comment]
1. 更新log 读取路径，
2. 对screenshot， applicaiton， element 系统私有库头文件升级
3. 更新macaca-ios 驱动

**Comment by SamuelZhaoY** [comment]
`>> responseHandler.js:11:12 [master] pid:14442 Recieve HTTP Request from Client[2017-09-26 09:35:26]: method: POST url: /wd/hub/session/e3c625ac-df63-4de2-874f-dab32e4d3f86/element/1004/click, jsonBody: {}
>> remote-debugger.js:63:12 [master] pid:14442 Getting pages from url: http://localhost:9222/json
>> client.js:115:14 [master] pid:14442 Send command to websocket: {"method":"Runtime.evaluate","params":{"expression":"(function(){return function(){var k,aa=this;function m(a){return void 0!==a}function ba(a,b){var c=a.split(\".\"),d=aa;c[0]in d||!d.execScript||d.execScript(\"var \"+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&m(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}}\nfunction ca(a){var b=typeof a;if(\"object\"==b)if(a){if(a instanceof Array)return\"array\"...
>> client.js:51:12 [master] pid:14442 Get result from websocket: {"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":null}"},"wasThrown":false},"id":9}
>> responseHandler.js:49:14 [master] pid:14442 Send HTTP Respone to Client[2017-09-26 09:35:26]: {"sessionId":"e3c625ac-df63-4de2-874f-dab32e4d3f86","status":0,"value":null}
>> client.js:51:12 [master] pid:14442 Get result from websocket: {"method":"Canvas.canvasMemoryChanged","params":{"canvasId":"canvas:0.2","memoryCost":1600000}}
>> xctest-client.js:41:14 [master] pid:14442 Uncaught Exception: TypeError: Cannot read property 'wasThrown' of undefined
>> xctest-client.js:277:14 [master] pid:14442 killing deviceLogProc pid: 14486
>> xctest-client.js:282:14 [master] pid:14442 killing runnerProc pid: 14457
`

web 场景下依然存在小范围不稳定性

**Comment by tudoufenzi** [comment]
问下 升级Xcode9 后，编译时提示这个，这两个缺少的文件没有找到，请问如何解决》？

ld: warning: directory not found for option '-F/Users/guyanpu/XCTestWD/XCTestWD/../Carthage/Build/iOS'
ld: framework not found Swifter
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tudoufenzi** [comment]
上午发的问题已解决，解决办法：
在xctestwd目录下找到 carfile文件，查看以来的第三方库
然后 执行  carthage update --platform iOS  命令，将第三方库重新拉取编译一遍就可以生成对应的文件
再次编译build 就正常了

**Comment by Jupengpeng** [comment]
很惊喜看到更新适配Xcode9！
然而我尝试编译 target XCTestWDUITests
报错：Type of property 'unsigned long long' in class extension does not match property type in primary class；
然后我注释：@property unsigned long long state; // @synthesize state=_state;
报错：	"_OBJC_CLASS_$_XCAccessibilityElement", referenced from:
	Linker command failed with exit code 1 (use -v to see invocation)，很迷惑

**Comment by SamuelZhaoY** [comment]
@tudoufenzi carthage 编译是不够的， 因为本身的私有库头文件冲突， 待合并的版本中更新了头文件

**Comment by SamuelZhaoY** [comment]
@Jupengpeng 目前这个问题已经解决，正在测试，验证稳定性.  由于xcode9 中测试库改动较大，所以测试时间相对比较长

**Comment by SamuelZhaoY** [comment]
已发布 xcode9 xctestwd 版本， 请更新
