### ISSUE TITLE
xctestwd的tap有点慢，借用fb的wda能提升速度，oc代码已经构建，转成swift后再pr

### ISSUE THREAD

**Issue by adudurant** [macacajs/XCTestWD#92]
如题

**Comment by adudurant** [comment]
对应的uirecorde可以做修改，不做findelement的请求(消耗很多实际)，全部采用坐标点击，整个录制回放时间目测可以优化8成

**Comment by pluie-cloud** [comment]
@adudurant 是不是更新项目 就可以了

**Comment by SamuelZhaoY** [comment]
"对应的uirecorde可以做修改，不做findelement的请求(消耗很多实际)，全部采用坐标点击，整个录制回放时间目测可以优化8成" 不符合 web driver 规范.  协议中有规定需要支持 element 点击

**Comment by adudurant** [comment]
@SamuelZhaoY   只是提供点思路而已啦

**Comment by pluie-cloud** [comment]
我直接改了tap方法：发现差不多快了1-2s 按坐标点击
if elementId != "" {
           let element = XCTestWDSessionManager.commonCache.elementForUUID(elementId)
            if element != nil {
                if (element?.isHittable)! && (element?.exists)! {
                    element?.tap()
                }
                return XCTestWDResponse.response(session: nil, error: WDStatus.Success)
            }
        }else {
            let rawX = getFloatValue(target: request.jsonBody, field: "x")
            let rawY = getFloatValue(target: request.jsonBody, field: "y")
            .
            .
            .

**Comment by SamuelZhaoY** [comment]
@pluie-cloud 现在的实现也可以支持 xy 坐标点击的，可以直接传输 事件， 传入 xy 值

**Comment by adudurant** [comment]
@pluie-cloud   不符合协议 不建议   可自行用fb的来对比
