### ISSUE TITLE
使用Macaca测试ios真机，老是卸载安装好的xctestwd应用，然后提示'Connection aborted.'

### ISSUE THREAD

**Issue by xiaozhaoyi** [macacajs/XCTestWD#93]
详细日志如下：
Last login: Fri Sep 29 16:08:11 on ttys001
BruceMacBook-Air:~ ios3rd$ macaca server --verbose
>> index.js:18:12 [master] pid:14177 webdriver server start with config:
 { port: 3456,
  verbose: true,
  always: true,
  ip: '192.168.2.24',
  host: 'BruceMacBook-Air.local',
  loaded_time: '2017-09-29 18:58:09' }
>> middlewares.js:17:10 [master] pid:14177 base middlewares attached
>> router.js:127:10 [master] pid:14177 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:14177 Recieve HTTP Request from Client[2017-09-29 18:58:12]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"iOS","platformVersion":"10.3","deviceName":"iPhone","udid":"ca69a10239ebf0949b958dc731b5005c6cd2bbb3","bundleId":"com.tingting.cbb"}}
>> session.js:47:10 [master] pid:14177 Creating session, sessionId: 43999a7d-630c-47d2-b222-44d647712ce9.
/usr/local/lib/node_modules/macaca-ios/node_modules/_ios-device@0.1.4@ios-device/node_modules/ios-deploy/build/Release/ios-deploy
>> macaca-ios.js:246:12 [master] pid:14177 App "com.tingting.cbb" is already installed.
>> macaca-ios.js:247:12 [master] pid:14177 Adopting app reuse strategy: 1.
BundleId XCTestWD.XCTestWD does not exist.
>> macaca-ios.js:158:10 [master] pid:14177 {
	"bundleId": "com.tingting.cbb",
	"platformName": "iOS",
	"platformVersion": "10.3"
}
>> xctest-client.js:55:14 [master] pid:14177 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.1.8@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> macaca-ios.js:167:12 [master] pid:14177 Trying to start xctestwd server...
>> xctest-client.js:228:14 [master] pid:14177 xcode version: 8.3.3
>> XCTestWD version: 1.1.8
>> xctest-client.js:178:14 [master] pid:14177 2017-09-29 18:58:15.381 xcodebuild[14190:234690] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XAlign.xcplugin' not present in DVTPlugInCompatibilityUUIDs

>> xctest-client.js:179:14 [master] pid:14177 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.1.8@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:178:14 [master] pid:14177 2017-09-29 18:58:15.381 xcodebuild[14190:234690] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-09-29 18:58:15.382 xcodebuild[14190:234690] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KSImageNamed.xcplugin' not present in DVTPlugInCompatibilityUUIDs

>> xctest-client.js:179:14 [master] pid:14177 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.1.8@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:178:14 [master] pid:14177 2017-09-29 18:58:17.124 xcodebuild[14190:234755]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/ios3rd/Library/Developer/Xcode/DerivedData/XCTestWD-azfcbbijchqxicawalzewrlysecw/Logs/Test/4A811324-AB74-4E29-9E23-6B7749D7C261/Session-XCTestWDUITests-2017-09-29_185817-7zsi02.log

>> xctest-client.js:179:14 [master] pid:14177 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.1.8@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:178:14 [master] pid:14177 2017-09-29 18:58:17.125 xcodebuild[14190:234690] [MT] IDETestOperationsObserverDebug: (55FDD957-F41C-4DAD-8868-1D42ED7A2117) Beginning test session XCTestWDUITests-55FDD957-F41C-4DAD-8868-1D42ED7A2117 at 2017-09-29 18:58:17.124 with Xcode 8E3004b on target <DVTiOSDevice: 0x7ff6099180b0> {
		deviceSerialNumber:         F2MNH29CG5QQ
		identifier:                 ca69a10239ebf0949b958dc731b5005c6cd2bbb3
		deviceClass:                iPhone
		deviceName:                 iPhone
		deviceIdentifier:           ca69a10239ebf0949b958dc731b5005c6cd2bbb3
		productVersion:             10.1.1
		buildVersion:               14B100
		deviceSoftwareVersion:      10.1.1 (14B100)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        11852554240
		deviceAvailableCapacity:    5687496704
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7ff6094f7ed0 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		} (10.1.1 (14B100))

>> xctest-client.js:179:14 [master] pid:14177 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.1.8@xctestwd/XCTestWD/XCTestWD.xcodeproj

然后用例执行提示：requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

**Comment by adudurant** [comment]
本身编译xctestwd问题，建议先用xcode调试好
