### ISSUE TITLE
XCTestWD backward compatibility

### ISSUE THREAD

**Issue by SamuelZhaoY** [macacajs/XCTestWD#96]
provide backward compatibility for xcode 8.x  and iOS version 10.x and below

**Comment by Chan-Chun** [comment]
@SamuelZhaoY 解决方法：将依赖的framwork打成了一个npm包，https://github.com/macacajs/xctestwd-frameworks-9.1,当前工程已经不再发carthage checkout目录，这个打好的包按照用户所使用的版本来兼容。
