### ISSUE TITLE
XCTestWD 'source' response refine

### ISSUE THREAD

**Issue by SamuelZhaoY** [macacajs/XCTestWD#97]
去除无效的底层元素 e.g. <Button><Button><Button/><Button/> 
提升source 稳定性

**Comment by SamuelZhaoY** [comment]
真机稳定性 以及source 效率存在问题， 与模拟器表现差异很大， 模拟器source 操作可以再极短时间内完成.

**Comment by SamuelZhaoY** [comment]
https://github.com/facebook/WebDriverAgent/issues/744 similar issue. on real devices, source is slow and unstable

**Comment by adudurant** [comment]
感觉oc的要稳定些 不知道是不是语言差异
